name = "spirv-headers"
version = "1.4.357.0"
release = 1
description = "Machine-readable parts of the SPIR-V specification"
license = "MIT"
arch = "any"
url = "https://github.com/KhronosGroup/SPIRV-Headers"


build_deps = ['cmake', 'ninja']

[[sources]]
type = "http"
sha256 = "4d703067a7e06331ccb37bdfed3f9b7879cc61969a2689ae95c95db34a47ff07"
url = "https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/SPIRV-Headers-vulkan-sdk-${VERSION}
cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release'''

[pipeline.compile]
script = '''
cd source/SPIRV-Headers-vulkan-sdk-${VERSION}
cmake --build build -j $(nproc)'''

[pipeline.staging]
script = '''
cd source/SPIRV-Headers-vulkan-sdk-${VERSION}
DESTDIR=${STAGING_DIR} cmake --install build'''

