name = "gocryptfs"
version = "2.6.1"
release = 2
description = "Encrypted overlay filesystem written in Go"
license = "MIT"
arch = "x86_64"
url = "https://github.com/rfjakob/gocryptfs"

[dependencies]
runtime = ["libfuse3"]
build = ["go", "openssl", "pkgconf"]
link = ["openssl"]

[[sources]]
type = "git"
url = "https://github.com/rfjakob/gocryptfs.git"
ref = "v${VERSION}"
extract_to = "source"

[lifecycle.compile]
isolation = "relaxed"
script = '''
cd source/gocryptfs-*/
CGO_ENABLED=1 ./build.bash'''

[lifecycle.staging]
script = '''
cd source/gocryptfs-*/
make DESTDIR=${PART_DIR} install'''
