name = "gocryptfs"
version = "2.6.1"
release = 2
description = "Encrypted overlay filesystem written in Go"
license = "MIT"
arch = "x86_64"
url = "https://github.com/rfjakob/gocryptfs"

[dependencies]
runtime = ["libfuse3"]
build = ["go", "openssl", "pkgconf"]
link = ["openssl"]

[[sources]]
uri = "git+https://github.com/rfjakob/gocryptfs.git#v${VERSION}"
sha256 = "SKIP"

[lifecycle.compile]
dockyard = "relaxed"
script = '''
cd ${BUILD_DIR}/gocryptfs-*/
CGO_ENABLED=1 ./build.bash

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}/gocryptfs-*/
make DESTDIR=${PART_DIR} install

'''

[lifecycle.fabricate]
