name = "python-pyparsing"
version = "3.3.2"
release = 2
description = "Python parsing module"
license = "MIT"
arch = "any"
url = "https://github.com/pyparsing/pyparsing"


build_deps = ['python']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://files.pythonhosted.org/packages/source/p/pyparsing/pyparsing-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/pyparsing-${VERSION}
echo "python package"'''

[pipeline.compile]
script = '''
cd source/pyparsing-${VERSION}
echo "no build needed"'''

[pipeline.staging]
script = '''
cd source/pyparsing-${VERSION}
pip3 install --no-index --no-user --no-deps --ignore-installed --no-build-isolation --root=${STAGING_DIR} .'''

