name = "simde"
version = "0.8.2"
release = 1
description = "Implementations of SIMD instruction sets for non-native platforms"
license = "MIT"
arch = "x86_64"
url = "https://github.com/simd-everywhere/simde"


build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/simd-everywhere/simde/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/simde-${VERSION}
meson setup build \
    --prefix=/usr \
    --buildtype=release \
    -D tests=false'''

[pipeline.compile]
script = '''
cd source/simde-${VERSION}
ninja -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/simde-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

