name = "python-glad2"
version = "2.0.8"
release = 1
description = "Multi-language GL/GLES/EGL/GLX/WGL loader generator"
license = "MIT"
arch = "x86_64"
url = "https://github.com/Dav1dde/glad"

[dependencies]
build = ["python"]

[[sources]]
uri = "https://files.pythonhosted.org/packages/source/g/glad2/glad2-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
pip3 install --break-system-packages --no-deps --root=${PART_DIR} --no-build-isolation .

'''
