name = "libclc"
version = "22.1.8"
release = 1
description = "OpenCL C library implementation for LLVM"
license = "Apache-2.0"
arch = "x86_64"
url = "https://libclc.llvm.org/"

link_deps = ['llvm:llvm-libs']
build_deps = ['cmake', 'llvm:clang']

[[sources]]
type = "http"
sha256 = "922f1817a0df7b1489272d18134ee0087a8b068828f87ac63b9861b1a9965888"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-${VERSION}/llvm-project-${VERSION}.src.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/llvm-project-${VERSION}.src
mkdir build-libclc && cd build-libclc
cmake ../libclc                              \
-DCMAKE_INSTALL_PREFIX=/usr            \
-DCMAKE_BUILD_TYPE=Release'''

[pipeline.compile]
script = '''
cd source/llvm-project-${VERSION}.src/build-libclc
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/llvm-project-${VERSION}.src/build-libclc
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['glibc', 'llvm:llvm-libs']
