name = "libplacebo"
version = "7.360.0"
release = 1
description = "Reusable library for GPU-accelerated image/video processing"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://github.com/haasn/libplacebo"

link_deps = ['glslang', 'lcms2', 'shaderc', 'spirv-cross', 'vulkan-loader']
build_deps = ['vulkan-headers', 'meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://code.videolan.org/videolan/libplacebo/-/archive/v${VERSION}/libplacebo-v${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libplacebo-v${VERSION}
meson setup build \
--prefix=/usr \
--buildtype=release \
-D demos=false \
-D tests=false \
-D glslang=enabled \
-D shaderc=enabled \
-D vulkan=enabled \
-D lcms=enabled \
-D opengl=disabled'''

[pipeline.compile]
script = '''
cd source/libplacebo-v${VERSION}
ninja -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/libplacebo-v${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['glslang', 'lcms2', 'shaderc', 'spirv-cross', 'vulkan-loader']
