name = "pipewire"
version = "1.6.4"
release = 1
description = "Low-latency audio/video router and processor"
license = "MIT"
arch = "x86_64"
url = "https://pipewire.org"

link_deps = ['alsa-lib', 'bluez', 'dbus', 'glib', 'gstreamer', 'libcamera', 'libsndfile', 'ncurses', 'opus', 'readline', 'sbc', 'systemd', 'v4l-utils']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/PipeWire/pipewire/archive/refs/tags/${VERSION}.tar.gz"
extract_to = "source"

[pipeline.prepare]
script = "cd source"

[pipeline.configure]
script = '''
cd source/pipewire-${VERSION}
meson setup build \
--prefix=/usr                        \
--buildtype=release                  \
-D docs=disabled                     \
-D man=enabled                       \
-D tests=enabled                     \
-D gstreamer=enabled                 \
-D v4l2=enabled                      \
-D jack=disabled                     \
-D pipewire-jack=enabled             \
-D pipewire-alsa=enabled             \
-D libpulse=disabled                 \
-D pipewire-v4l2=enabled             \
-D rlimits-install=false             \
-D selinux=disabled                  \
-D udevrulesdir=/usr/lib/udev/rules.d \
-D bluez5=enabled                    \
-D libcamera=enabled                \
-D session-managers='''

[pipeline.compile]
script = '''
cd source/pipewire-${VERSION}
ninja -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/pipewire-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['alsa-lib', 'bluez', 'dbus', 'glib', 'gstreamer', 'libcamera', 'libsndfile', 'ncurses', 'opus', 'readline', 'sbc', 'systemd', 'v4l-utils']
hooks.post_install = '''
systemctl daemon-reload 2>/dev/null || true
systemd-tmpfiles --create /usr/lib/tmpfiles.d/pipewire.conf 2>/dev/null || true
'''
hooks.post_upgrade = "systemctl daemon-reload 2>/dev/null || true"
