name = "scdoc"
version = "1.11.3"
release = 1
description = "Simple man page generator"
license = "MIT"
arch = "x86_64"
url = "https://git.sr.ht/~sircmpwn/scdoc"

[[sources]]
sha256 = "SKIP"
url = "https://git.sr.ht/~sircmpwn/scdoc/archive/${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.compile]
script = '''
cd source
make PREFIX=/usr -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make PREFIX=/usr DESTDIR=${PART_DIR} install'''
