name = "libpsl"
version = "0.21.5"
release = 1
description = "Library for accessing the Public Suffix List"
license = "MIT"
arch = "x86_64"
url = "https://github.com/rockdaboot/libpsl"

[dependencies]
build = ["meson", "ninja"]
link = ["libidn2", "libunistring"]

[[sources]]
uri = "https://github.com/rockdaboot/libpsl/releases/download/${VERSION}/libpsl-${VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
meson setup ${BUILD_DIR}/build ${BUILD_DIR} \
--prefix=/usr         \
--buildtype=release

'''

[lifecycle.compile]
script = "ninja -C ${BUILD_DIR}/build -j$(nproc)"

[lifecycle.staging]
script = "DESTDIR=${PART_DIR} ninja -C ${BUILD_DIR}/build install"

[lifecycle.fabricate]
