name = "groff"
version = "1.24.1"
release = 1
description = "Programs for processing and formatting text and images"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/groff/"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/groff/groff-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/groff-${VERSION}
PAGE=A4 ./configure --prefix=/usr'''

[pipeline.compile]
script = '''
cd source/groff-${VERSION}
make -j1'''

[pipeline.staging]
script = '''
cd source/groff-${VERSION}
make DESTDIR=${STAGING_DIR} install'''
