name = "groff"
version = "1.23.0"
release = 1
description = "Programs for processing and formatting text and images"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/groff/"

[dependencies]
build = ["gcc", "make", "perl"]

[[sources]]
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/groff/groff-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
PAGE=A4 ./configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source
make -j1'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
