[plan]
name = "sof-firmware"
version = "2025.12.2"
release = 1
description = "Sound Open Firmware"
license = "BSD-3-Clause"
arch = "any"
url = "https://github.com/thesofproject/sof-bin"

[sources]
uris = ["https://github.com/thesofproject/sof-bin/releases/download/v${PKG_VERSION}/sof-bin-${PKG_VERSION}.tar.gz"]
sha256 = ["SKIP"]

[lifecycle.configure]
dockyard = "none"
script = '''
echo "firmware package"
'''

[lifecycle.compile]
dockyard = "none"
script = '''
echo "no build needed"
'''

[lifecycle.package]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
mkdir -p ${PKG_DIR}/usr/lib/firmware/intel
cp -a sof ${PKG_DIR}/usr/lib/firmware/intel/sof
cp -a sof-ipc4 ${PKG_DIR}/usr/lib/firmware/intel/sof-ipc4
cp -a sof-ipc4-lib ${PKG_DIR}/usr/lib/firmware/intel/sof-ipc4-lib
cp -a sof-tplg ${PKG_DIR}/usr/lib/firmware/intel/sof-tplg
cp -a sof-ace-tplg ${PKG_DIR}/usr/lib/firmware/intel/sof-ace-tplg
cp -a sof-ipc4-tplg ${PKG_DIR}/usr/lib/firmware/intel/sof-ipc4-tplg
'''
