name = "godot-bin"
version = "4.6.3"
release = 1
description = "Prebuilt upstream Godot Engine editor binary"
license = "MIT"
arch = "x86_64"
url = "https://godotengine.org"

[[sources]]
type = "http"
url = "https://github.com/godotengine/godot-builds/releases/download/${VERSION}-stable/Godot_v${VERSION}-stable_linux.x86_64.zip"
sha256 = "d0bc2113065e481c9c2c2b2c37daa4e8be3fe9e27f0ab9ab0b6096e9a37907f3"
extract_to = "source"

[[sources]]
type = "local"
path = "godot"

[[sources]]
type = "local"
path = "godot.6"

[[sources]]
type = "local"
path = "godot.compose"

[[sources]]
type = "local"
path = "godot.svg"

[[sources]]
type = "local"
path = "org.godotengine.Godot.appdata.xml"

[[sources]]
type = "local"
path = "org.godotengine.Godot.desktop"

[[sources]]
type = "local"
path = "org.godotengine.Godot.xml"

[pipeline.staging]
script = '''
install -Dm755 \
    ${WORKDIR}/source/Godot_v${VERSION}-stable_linux.x86_64 \
    ${STAGING_DIR}/usr/lib/godot-bin/godot

install -Dm755 \
    ${WORKDIR}/${NAME}-godot \
    ${STAGING_DIR}/usr/bin/godot
install -Dm644 \
    ${WORKDIR}/${NAME}-godot.compose \
    ${STAGING_DIR}/usr/share/godot-bin/godot.compose
install -Dm644 \
    ${WORKDIR}/${NAME}-godot.6 \
    ${STAGING_DIR}/usr/share/man/man6/godot.6
install -Dm644 \
    ${WORKDIR}/${NAME}-godot.svg \
    ${STAGING_DIR}/usr/share/icons/hicolor/scalable/apps/godot.svg
install -Dm644 \
    ${WORKDIR}/${NAME}-org.godotengine.Godot.appdata.xml \
    ${STAGING_DIR}/usr/share/metainfo/org.godotengine.Godot.appdata.xml
install -Dm644 \
    ${WORKDIR}/${NAME}-org.godotengine.Godot.desktop \
    ${STAGING_DIR}/usr/share/applications/org.godotengine.Godot.desktop
install -Dm644 \
    ${WORKDIR}/${NAME}-org.godotengine.Godot.xml \
    ${STAGING_DIR}/usr/share/mime/packages/org.godotengine.Godot.xml'''

[[output]]
runtime_deps = ['alsa-lib', 'dbus', 'desktop-file-utils', 'fontconfig', 'libdecor', 'libxkbcommon', 'mesa', 'pipewire', 'shared-mime-info', 'systemd', 'vulkan-loader', 'wayland']
replaces = ["godot"]

[output.hooks]
post_install = '''
update-desktop-database -q /usr/share/applications 2>/dev/null || true
update-mime-database /usr/share/mime >/dev/null 2>&1 || true'''
post_upgrade = '''
update-desktop-database -q /usr/share/applications 2>/dev/null || true
update-mime-database /usr/share/mime >/dev/null 2>&1 || true'''
