name = "libdisplay-info"
version = "0.2.0"
release = 1
description = "EDID and DisplayID library"
license = "MIT"
arch = "x86_64"
url = "https://gitlab.freedesktop.org/emersion/libdisplay-info"

[dependencies]
build = ["hwdata", "meson", "ninja"]

[[sources]]
uri = "https://gitlab.freedesktop.org/emersion/libdisplay-info/-/releases/${PART_VERSION}/downloads/libdisplay-info-${PART_VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
meson setup ${BUILD_DIR}/build ${BUILD_DIR} \
--prefix=/usr         \
--buildtype=release

'''

[lifecycle.compile]
script = "ninja -C ${BUILD_DIR}/build -j$(nproc)"

[lifecycle.staging]
script = "DESTDIR=${PART_DIR} ninja -C ${BUILD_DIR}/build install"

[lifecycle.fabricate]
