name = "libdisplay-info"
version = "0.2.0"
release = 1
description = "EDID and DisplayID library"
license = "MIT"
arch = "x86_64"
url = "https://gitlab.freedesktop.org/emersion/libdisplay-info"


build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://gitlab.freedesktop.org/emersion/libdisplay-info/-/releases/${VERSION}/downloads/libdisplay-info-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/libdisplay-info-${VERSION}
meson setup build \
--prefix=/usr         \
--buildtype=release'''

[lifecycle.compile]
script = '''
cd source/libdisplay-info-${VERSION}
ninja -C build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/libdisplay-info-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

