[plan]
name = "xz"
version = "5.8.2"
release = 1
description = "Programs for compressing and decompressing files in the XZ/LZMA format"
license = "GPL-2.0-or-later AND LGPL-2.1-or-later"
arch = "x86_64"
url = "https://tukaani.org/xz/"

[dependencies]
build = ["gcc", "make"]
[sources]
uris = ["https://github.com/tukaani-project/xz/releases/download/v${PKG_VERSION}/xz-${PKG_VERSION}.tar.xz"]
sha256 = ["SKIP"]

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr    \
--disable-static \
--docdir=/usr/share/doc/xz-${PKG_VERSION}
'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
'''

[lifecycle.check]
script = '''
cd ${BUILD_DIR}
make check
'''

[lifecycle.package]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PKG_DIR} install
'''
