name = "xz"
version = "5.8.3"
release = 1
description = "Programs for compressing and decompressing files in the XZ/LZMA format"
license = "GPL-2.0-or-later AND LGPL-2.1-or-later"
arch = "x86_64"
url = "https://tukaani.org/xz/"

[dependencies]
build = ["gcc", "make"]

[[sources]]
uri = "https://github.com/tukaani-project/xz/releases/download/v${PART_VERSION}/xz-${PART_VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr    \
--disable-static \
--docdir=/usr/share/doc/xz-${PART_VERSION}

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.check]
script = '''
cd ${BUILD_DIR}
make check

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install

'''

[lifecycle.fabricate]
