name = "xz"
version = "5.8.3"
release = 1
description = "Programs for compressing and decompressing files in the XZ/LZMA format"
license = "GPL-2.0-or-later AND LGPL-2.1-or-later"
arch = "x86_64"
url = "https://tukaani.org/xz/"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/tukaani-project/xz/releases/download/v${VERSION}/xz-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/xz-5.8.3
./configure --prefix=/usr    \
--disable-static \
--docdir=/usr/share/doc/xz-${VERSION}'''

[pipeline.compile]
script = '''
cd source/xz-5.8.3
make -j$(nproc)'''

[pipeline.check]
script = '''
cd source/xz-5.8.3
make check'''

[pipeline.staging]
script = '''
cd source/xz-5.8.3
make DESTDIR=${STAGING_DIR} install'''

