name = "libevdev"
version = "1.13.3"
release = 1
description = "Wrapper library for evdev input devices"
license = "MIT"
arch = "x86_64"
url = "https://www.freedesktop.org/wiki/Software/libevdev/"

[dependencies]
build = ["meson", "ninja"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://www.freedesktop.org/software/libevdev/libevdev-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup ${WORKDIR}/build ${WORKDIR} \
--prefix=/usr         \
--buildtype=release   \
-D documentation=disabled \
-D tests=disabled'''

[lifecycle.compile]
script = '''
cd source
ninja -C ${WORKDIR}/build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} ninja -C ${WORKDIR}/build install'''
