name = "libical"
version = "4.0.4"
release = 1
description = "Implementation of the iCalendar protocols and data formats"
license = "LGPL-2.1-only OR MPL-2.0"
arch = "x86_64"
url = "https://github.com/libical/libical"

link_deps = ['glibc', 'glib', 'icu', 'libxml2']
build_deps = ['ninja', 'cmake']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/libical/libical/archive/v${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/*
cmake -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBEXECDIR=lib \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_DISABLE_FIND_PACKAGE_BerkeleyDB=true \
    -DLIBICAL_GOBJECT_INTROSPECTION=false \
    -DLIBICAL_GLIB_VAPI=false \
    -DLIBICAL_GLIB_BUILD_DOCS=OFF \
    -DLIBICAL_JAVA_BINDINGS=OFF'''

[pipeline.compile]
script = '''
cd source/*
cmake --build build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/*
DESTDIR=${STAGING_DIR} cmake --install build'''

[[output]]
runtime_deps = ['glibc', 'glib', 'icu', 'libxml2']
