name = "tcl"
version = "8.6.17"
release = 1
description = "Tool Command Language - robust general-purpose scripting language"
license = "TCL"
arch = "x86_64"
url = "https://www.tcl.tk/"

[dependencies]
build = ["gcc", "make"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://downloads.sourceforge.net/project/tcl/Tcl/${VERSION}/tcl${VERSION}-src.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/unix
./configure --prefix=/usr           \
            --mandir=/usr/share/man \
            --disable-rpath'''

[lifecycle.compile]
script = '''
cd source/unix
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/unix
make DESTDIR=${PART_DIR} install
make DESTDIR=${PART_DIR} install-private-headers

ln -sfv tclsh8.6 ${PART_DIR}/usr/bin/tclsh
mv ${PART_DIR}/usr/share/man/man3/{Thread,Tcl_Thread}.3'''
