name = "libksba"
version = "1.6.7"
release = 1
description = "X.509 and CMS library for GnuPG"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://gnupg.org/software/libksba/"

[[sources]]
uri = "https://gnupg.org/ftp/gcrypt/libksba/libksba-${PART_VERSION}.tar.bz2"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr --disable-static

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
DESTDIR=${PART_DIR} make install

'''

[lifecycle.fabricate]
