name = "xkeyboard-config"
version = "2.46"
release = 1
description = "X Keyboard Configuration Database"
license = "MIT"
arch = "x86_64"
url = "https://www.freedesktop.org/wiki/Software/XKeyboardConfig/"

[dependencies]
build = ["meson", "ninja"]

[[sources]]
type = "http"
sha256 = "10c58218fb60d08fb1f7b30304deb3ba47613195aa8a08a81f1972775ccc3640"
url = "https://www.x.org/pub/individual/data/xkeyboard-config/xkeyboard-config-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
mkdir -p build && cd build
meson setup --prefix=/usr --buildtype=release ..'''

[lifecycle.compile]
script = '''
cd source/build
ninja'''

[lifecycle.staging]
script = '''
cd source/build
DESTDIR=${PART_DIR} ninja install'''
