name = "icu"
version = "78.2"
release = 1
description = "International Components for Unicode"
license = "ICU"
arch = "x86_64"

[dependencies]
build = ["gcc", "make", "python"]

[[sources]]
uri = "https://github.com/unicode-org/icu/releases/download/release-78.2/icu4c-78.2-sources.tgz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
# ICU 的源码位于解压后的 source 子目录中
cd ${BUILD_DIR}/source
./configure --prefix=/usr --sbindir=/usr/bin --disable-static --enable-tests=no --enable-samples=no

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}/source
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}/source
make DESTDIR=${PART_DIR} install

'''

[lifecycle.fabricate]
