name = "m4"
version = "1.4.21"
release = 1
description = "GNU macro processor used as a build tool for other programs"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/m4/"

[dependencies]
build = ["gcc", "make"]

[[sources]]
uri = "https://ftp.gnu.org/gnu/m4/m4-${VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.check]
script = '''
cd ${BUILD_DIR}
make check

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install
rm -f ${PART_DIR}/usr/share/info/dir

'''

[lifecycle.fabricate]
