[plan]
name = "patch"
version = "2.8"
release = 1
description = "A program for modifying or creating files by applying a patch file"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://savannah.gnu.org/projects/patch/"

[dependencies]
build = ["gcc", "make"]
[sources]
uris = ["https://ftp.gnu.org/gnu/patch/patch-${PKG_VERSION}.tar.xz"]
sha256 = ["SKIP"]

[lifecycle.configure]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr
'''

[lifecycle.compile]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
'''

[lifecycle.check]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make check
'''

[lifecycle.package]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PKG_DIR} install
'''
