name = "pkgconf"
version = "2.3.0"
release = 1
description = "Utility for discovering compiler and linker flags"
license = "ISC"
arch = "x86_64"
url = "https://pkgconf.org/"

[dependencies]
build = ["bash", "gcc", "make"]

[[sources]]
uri = "https://distfiles.ariadne.space/pkgconf/pkgconf-${PART_VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr --disable-static

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install

'''

[lifecycle.fabricate]
