name = "git"
version = "2.53.0"
release = 5
description = "The fast distributed version control system"
license = "GPL-2.0-only"
arch = "x86_64"
url = "https://git-scm.com/"

link_deps = ['curl', 'expat', 'openssl', 'pcre2', 'zlib-ng', 'libsecret']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://www.kernel.org/pub/software/scm/git/git-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.compile]
script = '''
cd source/git-${VERSION}

_perllibdir=$(/usr/bin/perl -MConfig -wle 'print $Config{installvendorlib}')

make \
  prefix=/usr \
  gitexecdir=/usr/lib/git-core \
  perllibdir="${_perllibdir}" \
  CFLAGS="${CFLAGS}" \
  LDFLAGS="${LDFLAGS}" \
  INSTALL_SYMLINKS=1 \
  MAN_BOLD_LITERAL=1 \
  NO_PERL_CPAN_FALLBACKS=1 \
  USE_LIBPCRE2=1 \
  ZLIB_NG=1 \
  WITH_RUST=1 \
  NO_ASCIIDOC=1 \
  NO_MAN=1 \
  all

make \
  prefix=/usr \
  gitexecdir=/usr/lib/git-core \
  perllibdir="${_perllibdir}" \
  CFLAGS="${CFLAGS}" \
  LDFLAGS="${LDFLAGS}" \
  INSTALL_SYMLINKS=1 \
  MAN_BOLD_LITERAL=1 \
  NO_PERL_CPAN_FALLBACKS=1 \
  USE_LIBPCRE2=1 \
  ZLIB_NG=1 \
  WITH_RUST=1 \
  NO_ASCIIDOC=1 \
  NO_MAN=1 \
  -C contrib/credential/libsecret

make \
  prefix=/usr \
  gitexecdir=/usr/lib/git-core \
  perllibdir="${_perllibdir}" \
  CFLAGS="${CFLAGS}" \
  LDFLAGS="${LDFLAGS}" \
  INSTALL_SYMLINKS=1 \
  MAN_BOLD_LITERAL=1 \
  NO_PERL_CPAN_FALLBACKS=1 \
  USE_LIBPCRE2=1 \
  ZLIB_NG=1 \
  WITH_RUST=1 \
  NO_ASCIIDOC=1 \
  NO_MAN=1 \
  -C contrib/subtree all

make \
  prefix=/usr \
  gitexecdir=/usr/lib/git-core \
  perllibdir="${_perllibdir}" \
  CFLAGS="${CFLAGS}" \
  LDFLAGS="${LDFLAGS}" \
  INSTALL_SYMLINKS=1 \
  MAN_BOLD_LITERAL=1 \
  NO_PERL_CPAN_FALLBACKS=1 \
  USE_LIBPCRE2=1 \
  ZLIB_NG=1 \
  WITH_RUST=1 \
  NO_ASCIIDOC=1 \
  NO_MAN=1 \
  -C contrib/diff-highlight'''

[pipeline.staging]
script = '''
cd source/git-${VERSION}

_perllibdir=$(/usr/bin/perl -MConfig -wle 'print $Config{installvendorlib}')

make \
  DESTDIR=${STAGING_DIR} \
  prefix=/usr \
  gitexecdir=/usr/lib/git-core \
  perllibdir="${_perllibdir}" \
  CFLAGS="${CFLAGS}" \
  LDFLAGS="${LDFLAGS}" \
  INSTALL_SYMLINKS=1 \
  MAN_BOLD_LITERAL=1 \
  NO_PERL_CPAN_FALLBACKS=1 \
  USE_LIBPCRE2=1 \
  ZLIB_NG=1 \
  WITH_RUST=1 \
  NO_ASCIIDOC=1 \
  NO_MAN=1 \
  install

# bash completion
mkdir -p ${STAGING_DIR}/usr/share/bash-completion/completions/
install -m 0644 ./contrib/completion/git-completion.bash \
  ${STAGING_DIR}/usr/share/bash-completion/completions/git

# git prompt
mkdir -p ${STAGING_DIR}/usr/share/git/
install -m 0644 ./contrib/completion/git-prompt.sh \
  ${STAGING_DIR}/usr/share/git/git-prompt.sh

# libsecret credentials helper
install -m 0755 contrib/credential/libsecret/git-credential-libsecret \
  ${STAGING_DIR}/usr/lib/git-core/git-credential-libsecret
make \
  prefix=/usr \
  gitexecdir=/usr/lib/git-core \
  perllibdir="${_perllibdir}" \
  CFLAGS="${CFLAGS}" \
  LDFLAGS="${LDFLAGS}" \
  INSTALL_SYMLINKS=1 \
  MAN_BOLD_LITERAL=1 \
  NO_PERL_CPAN_FALLBACKS=1 \
  USE_LIBPCRE2=1 \
  ZLIB_NG=1 \
  WITH_RUST=1 \
  NO_ASCIIDOC=1 \
  NO_MAN=1 \
  -C contrib/credential/libsecret clean

# subtree install
make \
  DESTDIR=${STAGING_DIR} \
  prefix=/usr \
  gitexecdir=/usr/lib/git-core \
  perllibdir="${_perllibdir}" \
  CFLAGS="${CFLAGS}" \
  LDFLAGS="${LDFLAGS}" \
  INSTALL_SYMLINKS=1 \
  MAN_BOLD_LITERAL=1 \
  NO_PERL_CPAN_FALLBACKS=1 \
  USE_LIBPCRE2=1 \
  ZLIB_NG=1 \
  WITH_RUST=1 \
  NO_ASCIIDOC=1 \
  NO_MAN=1 \
  -C contrib/subtree install

# contrib extras
find contrib/ -name '.gitignore' -delete
cp -a ./contrib/* ${STAGING_DIR}/usr/share/git/

# zsh completion (merged into main package)
install -d ${STAGING_DIR}/usr/share/zsh/site-functions/
ln -s ../../git/completion/git-completion.zsh \
  ${STAGING_DIR}/usr/share/zsh/site-functions/_git'''

[[output]]
runtime_deps = ['ca-certificates', 'curl', 'expat', 'perl', 'openssl', 'pcre2', 'grep', 'shadow', 'zlib-ng', 'openssh', 'libsecret']
