name = "mdadm"
version = "4.4"
release = 1
description = "Tool for creating, managing, and monitoring Linux MD RAID arrays"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://www.kernel.org/pub/linux/utils/raid/mdadm/"

link_deps = ['systemd', 'util-linux']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://www.kernel.org/pub/linux/utils/raid/mdadm/mdadm-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.compile]
script = '''
cd source
make CWFLAGS="-Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIE -Warray-bounds -Wimplicit-fallthrough=0 -Wno-error=implicit-fallthrough -Wno-error=unterminated-string-initialization"'''

[lifecycle.staging]
script = '''
cd source
make \
  DESTDIR=${STAGING_DIR} \
  BINDIR=/usr/bin \
  SBINDIR=/usr/bin \
  install

if [ -d ${STAGING_DIR}/usr/etc ]; then
  mkdir -p ${STAGING_DIR}/etc
  cp -a ${STAGING_DIR}/usr/etc/. ${STAGING_DIR}/etc/
  rm -rf ${STAGING_DIR}/usr/etc
fi'''

[[output]]
runtime_deps = ['systemd', 'util-linux']
