name = "less"
version = "692"
release = 1
description = "A text file viewer"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.greenwoodsoftware.com/less/"

link_deps = ['ncurses']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://www.greenwoodsoftware.com/less/less-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/less-${VERSION}
./configure --prefix=/usr --sysconfdir=/etc'''

[pipeline.compile]
script = '''
cd source/less-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/less-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['ncurses']
