name = "glib"
version = "2.88.1"
release = 1
description = "Core application building blocks library"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://www.gtk.org/"

link_deps = ['libffi', 'pcre2', 'util-linux', 'zlib']
build_deps = ['meson', 'ninja', 'pkgconf']

[[sources]]
type = "http"
sha256 = "51ab804c56f6eab3e5045c774d1290ac5e4c923d4f9a3d8e33123bee45c1840e"
url = "https://download.gnome.org/sources/glib/2.88/glib-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/glib-${VERSION}
meson setup build \
    --prefix=/usr \
    --buildtype=release \
    --wrap-mode=nodownload \
    -Ddefault_library=shared \
    -Dtests=false \
    -Dinstalled_tests=false \
    -Dman-pages=disabled \
    -Ddocumentation=false \
    -Dintrospection=disabled \
    -Dlibmount=enabled \
    -Dlibelf=disabled \
    -Dselinux=disabled \
    -Dsysprof=disabled \
    -Dnls=disabled \
    -Dxattr=true \
    -Dglib_debug=disabled \
    -Dglib_assert=true \
    -Dglib_checks=true \
    -Dfile_monitor_backend=inotify'''

[lifecycle.compile]
script = '''
cd source/glib-${VERSION}
meson compile -C build'''

[lifecycle.staging]
script = '''
cd source/glib-${VERSION}
DESTDIR=${STAGING_DIR} meson install -C build'''

[[output]]
runtime_deps = ['libffi', 'pcre2', 'util-linux', 'zlib']
