name = "libgcrypt"
version = "1.12.1"
release = 1
description = "GnuPG cryptographic library"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://gnupg.org/software/libgcrypt/"

[dependencies]
build = ["pkgconf"]
link = ["libgpg-error"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-${VERSION}.tar.bz2"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr --disable-static'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} make install'''
