name = "libgcrypt"
version = "1.12.1"
release = 1
description = "GnuPG cryptographic library"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://gnupg.org/software/libgcrypt/"

[dependencies]
build = ["pkgconf"]
link = ["libgpg-error"]

[[sources]]
uri = "https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-${VERSION}.tar.bz2"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr --disable-static

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
DESTDIR=${PART_DIR} make install

'''

[lifecycle.fabricate]
