name = "pango"
version = "1.57.1"
release = 1
description = "Text layout and rendering library"
license = "LGPL-2.0-or-later"
arch = "x86_64"
url = "https://pango.gnome.org"

link_deps = ['glib', 'cairo', 'harfbuzz', 'fontconfig', 'fribidi', 'freetype']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/pango/1.57/pango-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/pango-${VERSION}
meson setup build \
--prefix=/usr               \
--buildtype=release         \
--wrap-mode=nofallback      \
-D xft=disabled             \
-D introspection=enabled'''

[pipeline.compile]
script = '''
cd source/pango-${VERSION}
ninja -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/pango-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['glib', 'cairo', 'harfbuzz', 'fontconfig', 'fribidi', 'freetype']
