name = "gtk-doc"
version = "1.35.1"
release = 1
description = "Documentation tool for public APIs of GTK+ and GNOME libraries"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://gitlab.gnome.org/GNOME/gtk-doc"

[dependencies]
runtime = [
    "docbook-xml",
    "docbook-xsl",
    "itstool",
    "libxslt",
    "python-pygments",
]
build = ["meson", "ninja", "pkgconf"]
link = ["glib"]

[[sources]]
uri = "https://download.gnome.org/sources/gtk-doc/1.35/gtk-doc-${PART_VERSION}.tar.xz"
sha256 = "611c9f24edd6d88a8ae9a79d73ab0dc63c89b81e90ecc31d6b9005c5f05b25e2"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
meson setup build \
  --prefix=/usr \
  -Dtests=false

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
ninja -C build

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
DESTDIR=${PART_DIR} ninja -C build install

'''

[lifecycle.fabricate]
