name = "python-pyproject-metadata"
version = "0.11.0"
release = 1
description = "PEP 621 project metadata parser"
license = "MIT"
arch = "x86_64"
url = "https://github.com/pypa/pyproject-metadata"

[dependencies]
runtime = ["python", "python-packaging"]
build = ["flit-core", "python", "python-packaging"]

[[sources]]
sha256 = "SKIP"
url = "https://pypi.org/packages/source/p/pyproject_metadata/pyproject_metadata-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .'''
