name = "shaderc"
version = "2026.2"
release = 1
description = "Google shaderc (glslc) compiler and SPIR-V tools"
license = "Apache-2.0"
arch = "x86_64"
url = "https://github.com/google/shaderc"

link_deps = ['spirv-tools', 'glslang']
build_deps = ['cmake', 'ninja', 'pkgconf', 'asciidoctor', 'python']

[[sources]]
type = "http"
sha256 = "f924178e75e3293082481b25ed64d5e48a795b479dac3bd3c83d23070855df42"
url = "https://github.com/google/shaderc/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[pipeline.prepare]
script = '''
cd source/shaderc-${VERSION}

# De-vendor libs and disable git versioning like Arch's PKGBUILD
sed '/examples/d;/third_party/d' -i CMakeLists.txt
sed '/build-version/d' -i glslc/CMakeLists.txt

spirv_tools_ver=$(pkg-config --modversion spirv-tools 2>/dev/null || pkg-config --modversion SPIRV-Tools 2>/dev/null || echo unknown)
glslang_ver=$(pkg-config --modversion glslang 2>/dev/null || echo unknown)

cat <<- BUILDVER_EOF > glslc/src/build-version.inc
"${VERSION}\\n"
"${spirv_tools_ver}\\n"
"${glslang_ver}\\n"
BUILDVER_EOF'''

[pipeline.configure]
script = '''
cd source/shaderc-${VERSION}
cmake -B build -S . -G Ninja \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_FLAGS="${CXXFLAGS} -ffat-lto-objects" \
    -DSHADERC_SKIP_TESTS=ON \
    -DPYTHON_EXECUTABLE=python \
    -Dglslang_SOURCE_DIR=/usr/include/glslang'''

[pipeline.compile]
script = '''
cd source/shaderc-${VERSION}
cmake --build build

cd glslc
asciidoctor -b manpage README.asciidoc -o glslc.1'''

[pipeline.staging]
script = '''
cd source/shaderc-${VERSION}
DESTDIR=${STAGING_DIR} cmake --install build
install -Dm 644 glslc/glslc.1 ${STAGING_DIR}/usr/share/man/man1/glslc.1
rm -f ${STAGING_DIR}/usr/lib/pkgconfig/shaderc_static.pc'''

[[output]]
runtime_deps = ['glslang', 'spirv-tools']
provides = ["glslc"]
