name = "gobject-introspection"
version = "1.86.0"
release = 1
description = "Introspection system for GObject-based libraries"
license = "LGPL-2.0-or-later"
arch = "x86_64"
url = "https://gi.readthedocs.io/"

[dependencies]
runtime = ["python"]
build = ["meson", "ninja", "python"]
link = ["glib"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/gobject-introspection/1.86/gobject-introspection-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build        \
--prefix=/usr            \
--buildtype=release'''

[lifecycle.compile]
script = '''
cd source
meson compile -C ${WORKDIR}/build'''

[lifecycle.staging]
script = '''
cd source
meson install -C ${WORKDIR}/build --destdir ${PART_DIR}'''
