name = "openjpeg"
version = "2.5.3"
release = 1
description = "Open-source JPEG 2000 codec"
license = "BSD-2-Clause"
arch = "x86_64"

[dependencies]
build = ["cmake", "gcc", "make"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/uclouvain/openjpeg/archive/v${VERSION}/openjpeg-v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_STATIC_LIBS=OFF -DBUILD_DOC=OFF -DBUILD_TESTING=OFF'''

[lifecycle.compile]
script = '''
cd source
cmake --build ${WORKDIR}/build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} cmake --install ${WORKDIR}/build'''
