name = "starship"
version = "1.25.1"
release = 1
description = "The minimal, blazing-fast, and infinitely customizable prompt for any shell"
license = "ISC"
arch = "x86_64"
url = "https://starship.rs/"

build = ['rust']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/starship/starship/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.compile]
isolation = "relaxed"
env = { CARGO_HOME = '${WORKDIR}/.cargo', CARGO_TARGET_DIR = '${WORKDIR}/target' }
script = '''
cd source/starship-${VERSION}
cargo build --release --locked'''

[lifecycle.staging]
script = '''
install -Dm755 ${WORKDIR}/target/release/starship ${PART_DIR}/usr/bin/starship
install -dm755 ${PART_DIR}/usr/share/bash-completion/completions
install -dm755 ${PART_DIR}/usr/share/zsh/site-functions
install -dm755 ${PART_DIR}/usr/share/fish/vendor_completions.d
${WORKDIR}/target/release/starship completions bash > ${PART_DIR}/usr/share/bash-completion/completions/starship
${WORKDIR}/target/release/starship completions zsh  > ${PART_DIR}/usr/share/zsh/site-functions/_starship
${WORKDIR}/target/release/starship completions fish > ${PART_DIR}/usr/share/fish/vendor_completions.d/starship.fish'''

