name = "spice-protocol"
version = "0.14.5"
release = 1
description = "SPICE protocol headers"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://www.spice-space.org/"

[dependencies]
build = ["meson", "ninja"]

[[sources]]
uri = "https://www.spice-space.org/download/releases/spice-protocol-${VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
meson setup build --prefix=/usr

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
ninja -C build

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
DESTDIR=${PART_DIR} ninja -C build install

'''

[lifecycle.fabricate]
