name = "spice-protocol"
version = "0.14.5"
release = 1
description = "SPICE protocol headers"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://www.spice-space.org/"

[dependencies]
build = ["meson", "ninja"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://www.spice-space.org/download/releases/spice-protocol-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source
ninja -C build'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} ninja -C build install'''
