[plan]
name = "btop"
version = "1.4.6"
release = 1
description = "A monitor of system resources, bpytop ported to C++"
license = "Apache-2.0"
arch = "x86_64"
url = "https://github.com/aristocratos/btop"

[dependencies]
build = ["gcc", "make", "libcap", "libdrm"]
link = ["libdrm"]

[[sources]]
uri = "https://github.com/aristocratos/btop/archive/refs/tags/v${PKG_VERSION}/btop-${PKG_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make all -j$(nproc)
'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PKG_DIR} PREFIX=/usr install
'''

[lifecycle.fabricate]
hooks.post_install = "setcap 'cap_perfmon=+ep' /usr/bin/btop"
hooks.post_upgrade = "setcap 'cap_perfmon=+ep' /usr/bin/btop"
