name = "man-db"
version = "2.13.1"
release = 3
description = "Programs for finding and viewing man pages"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://man-db.nongnu.org/"

[dependencies]
runtime = ["gdbm", "groff", "libpipeline"]
build = ["gcc", "gdbm", "groff", "libpipeline", "make"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.savannah.gnu.org/releases/man-db/man-db-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr                           \
--sbindir=/usr/bin                          \
--docdir=/usr/share/doc/man-db-${VERSION} \
--sysconfdir=/etc                       \
--disable-setuid                        \
--enable-cache-owner=bin                \
--with-browser=/usr/bin/lynx            \
--with-vgrind=/usr/bin/vgrind           \
--with-grap=/usr/bin/grap'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.check]
script = '''
cd source
make check'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
