name = "iw"
version = "6.9"
release = 1
description = "nl80211 based CLI configuration utility for wireless devices"
license = "ISC"
arch = "x86_64"
url = "https://wireless.wiki.kernel.org/en/users/documentation/iw"

[dependencies]
runtime = ["libnl"]
build = ["gcc", "libnl", "make"]

[[sources]]
uri = "https://www.kernel.org/pub/software/network/iw/iw-${VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make PREFIX=/usr -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make PREFIX=/usr DESTDIR=${PART_DIR} install

'''

[lifecycle.fabricate]
