name = "python-yaml"
version = "6.0.2"
release = 1
description = "YAML parser and emitter for Python"
license = "MIT"
arch = "x86_64"
url = "https://pyyaml.org/"

[dependencies]
build = ["python"]

[[sources]]
uri = "https://files.pythonhosted.org/packages/source/p/pyyaml/pyyaml-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
pip3 install --break-system-packages --no-deps --root=${PART_DIR} --no-build-isolation .

'''

[lifecycle.fabricate]
