name = "polkit"
version = "126"
release = 2
description = "Application-level toolkit for defining and handling authorization"
license = "LGPL-2.0-or-later"
arch = "x86_64"
url = "https://github.com/polkit-org/polkit"

[dependencies]
runtime = ["dbus", "systemd"]
build = ["meson", "ninja", "pkgconf"]
link = ["glib", "duktape", "linux-pam"]

[[sources]]
uri = "https://github.com/polkit-org/polkit/archive/refs/tags/${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
meson setup ${BUILD_DIR}/build ${BUILD_DIR} \
    --prefix=/usr               \
    --buildtype=release         \
    -D authfw=pam               \
    -D session_tracking=logind  \
    -D man=false                \
    -D tests=false              \
    -D introspection=false      \
    -D gtk_doc=false            \
    -D os_type=lfs              \
    -D examples=false

'''

[lifecycle.compile]
script = "ninja -C ${BUILD_DIR}/build -j$(nproc)"

[lifecycle.staging]
script = "DESTDIR=${PART_DIR} ninja -C ${BUILD_DIR}/build install"

[hooks]
post_install = '''
groupadd -fg 27 polkitd 2>/dev/null || true
useradd -r -u 27 -g polkitd -d /var/lib/polkit-1 -s /usr/bin/false \
    -c "PolicyKit Daemon Owner" polkitd 2>/dev/null || true

'''
