name = "expect"
version = "5.45.4"
release = 1
description = "Tools for automating interactive applications via scripted dialogues"
license = "Public Domain"
arch = "x86_64"
url = "https://core.tcl.tk/expect/"

[dependencies]
runtime = ["tcl"]
build = ["gcc", "make", "tcl"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://downloads.sourceforge.net/project/expect/Expect/${VERSION}/expect${VERSION}.tar.gz"
extract_to = "source"

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://www.linuxfromscratch.org/patches/lfs/12.4/expect-${VERSION}-gcc15-1.patch"

[lifecycle.prepare]
script = '''
cd source
patch -Np1 < ${WORKDIR}/expect-${VERSION}-gcc15-1.patch'''

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr           \
--with-tcl=/usr/lib     \
--enable-shared         \
--disable-rpath         \
--mandir=/usr/share/man \
--with-tclinclude=/usr/include'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.check]
script = '''
cd source
make test'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install
ln -svf expect${VERSION}/libexpect${VERSION}.so ${PART_DIR}/usr/lib'''
