name = "lzo"
version = "2.10"
release = 1
description = "Portable lossless data compression library"
license = "GPL-2.0"
arch = "x86_64"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://www.oberhumer.com/opensource/lzo/download/lzo-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/lzo-${VERSION}
./configure --prefix=/usr --enable-shared --disable-static --docdir=/usr/share/doc/lzo-${VERSION}'''

[lifecycle.compile]
script = "cd source/lzo-${VERSION} && make -j$(nproc)"

[lifecycle.staging]
script = "cd source/lzo-${VERSION} && make DESTDIR=${STAGING_DIR} install"

