name = "json-glib"
version = "1.10.8"
release = 2
description = "JSON parser/generator for GLib"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://wiki.gnome.org/Projects/JsonGlib"

link_deps = ['glib']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/json-glib/1.10/json-glib-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/json-glib-${VERSION}
meson setup build \
    --prefix=/usr             \
    --buildtype=release       \
    -Dtests=false             \
    -Dintrospection=enabled   \
    -Dman=false'''

[pipeline.compile]
script = '''
cd source/json-glib-${VERSION}
ninja -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/json-glib-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['glib']
