[plan]
name = "ninja"
version = "1.13.1"
release = 1
description = "Small build system with a focus on speed"
license = "Apache-2.0"
arch = "x86_64"
url = "https://ninja-build.org/"

[dependencies]
build = ["gcc", "python"]
[sources]
uris = ["https://github.com/ninja-build/ninja/archive/v1.13.1/ninja-1.13.1.tar.gz"]
sha256 = [
    "f0055ad0369bf2e372955ba55128d000cfcc21777057806015b45e4accbebf23",
]

[lifecycle.prepare]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
sed -i '/int Guess/a \
int   j = 0;\
char* jobs = getenv( "NINJAJOBS" );\
if ( jobs != NULL ) j = atoi( jobs );\
if ( j > 0 ) return j;\
' src/ninja.cc
'''

[lifecycle.compile]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
python3 configure.py --bootstrap --verbose
'''

[lifecycle.package]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
mkdir -p ${PKG_DIR}/usr/bin
mkdir -p ${PKG_DIR}/usr/share/bash-completion/completions
mkdir -p ${PKG_DIR}/usr/share/zsh/site-functions
install -vm755 ninja ${PKG_DIR}/usr/bin/ninja
install -vm644 misc/bash-completion ${PKG_DIR}/usr/share/bash-completion/completions/ninja
install -vm644 misc/zsh-completion ${PKG_DIR}/usr/share/zsh/site-functions/_ninja
'''
