name = "trash-cli"
version = "0.24.5.26"
release = 1
description = "Command line trashcan (recycle bin) interface"
license = "GPL-2.0-only"
arch = "any"
url = "https://github.com/andreafrancia/trash-cli"


build_deps = ['python']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://files.pythonhosted.org/packages/source/t/trash-cli/trash_cli-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.staging]
script = '''
cd source/trash-cli-${VERSION}
pip3 install --no-index --no-user --no-deps --ignore-installed --no-build-isolation --root=${STAGING_DIR} .'''

[[output]]
runtime_deps = ['python', 'python-psutil']
