name = "enchant"
version = "2.8.15"
release = 1
description = "Generic spell checking library"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://github.com/AbiWord/enchant"

link_deps = ['glib']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/AbiWord/enchant/releases/download/v${VERSION}/enchant-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/enchant-${VERSION}
./configure --prefix=/usr --sysconfdir=/etc --disable-static --with-groff'''

[pipeline.compile]
script = '''
cd source/enchant-${VERSION}
make'''

[pipeline.staging]
script = '''
cd source/enchant-${VERSION}
install -dm755 ${STAGING_DIR}/usr/lib/enchant-2
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['glib']
