name = "libffi"
version = "3.5.2"
release = 1
description = "Portable foreign function interface library"
license = "MIT"
arch = "x86_64"
url = "https://sourceware.org/libffi/"

[dependencies]
build = ["bash", "gcc", "make"]

[[sources]]
sha256 = "SKIP"
url = "https://github.com/libffi/libffi/releases/download/v${VERSION}/libffi-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr --disable-static'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
