name = "python-docutils"
version = "0.22.4"
release = 1
description = "Python documentation utilities"
license = "BSD-2-Clause AND GPL-3.0-or-later AND PSF-2.0"
arch = "x86_64"
url = "https://docutils.sourceforge.io/"

[dependencies]
runtime = ["python"]
build = ["python", "flit-core"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://pypi.org/packages/source/d/docutils/docutils-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .'''
