name = "slirp4netns"
version = "1.3.3"
release = 1
description = "User-mode networking for unprivileged network namespaces"
license = "GPL-2.0-only"
arch = "x86_64"
url = "https://github.com/rootless-containers/slirp4netns"

link_deps = ['glib', 'libcap', 'libseccomp', 'libslirp']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/rootless-containers/slirp4netns/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/slirp4netns-${VERSION}
./autogen.sh
./configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source/slirp4netns-${VERSION}
make -j$(nproc) -C ${WORKDIR}'''

[lifecycle.staging]
script = '''
cd source/slirp4netns-${VERSION}
make DESTDIR=${STAGING_DIR} install -C ${WORKDIR}'''

[[output]]
runtime_deps = ['glib', 'libcap', 'libseccomp', 'libslirp']
