name = "slirp4netns"
version = "1.3.3"
release = 1
description = "User-mode networking for unprivileged network namespaces"
license = "GPL-2.0-only"
arch = "x86_64"
url = "https://github.com/rootless-containers/slirp4netns"

[dependencies]
build = ["autoconf", "automake", "pkgconf"]
link = ["glib", "libcap", "libseccomp", "libslirp"]

[[sources]]
sha256 = "SKIP"
url = "https://github.com/rootless-containers/slirp4netns/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./autogen.sh
./configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc) -C ${WORKDIR}'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install -C ${WORKDIR}'''
