name = "libmnl"
version = "1.0.5"
release = 1
description = "Minimalistic Netlink userspace library"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://www.netfilter.org/projects/libmnl/"

[dependencies]
build = ["gcc", "make"]
link = ["glibc"]

[[sources]]
uri = "https://www.netfilter.org/pub/libmnl/libmnl-${PART_VERSION}.tar.bz2"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr --disable-static

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install

'''
