name = "libsoup"
version = "3.6.6"
release = 1
description = "HTTP client/server library for GNOME"
license = "LGPL-2.1-or-later"
arch = "x86_64"

link_deps = ['glib', 'libpsl', 'libxml2', 'nghttp2', 'sqlite']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/libsoup/3.6/libsoup-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libsoup-${VERSION}
meson setup build --prefix=/usr --buildtype=release -Dvapi=disabled -Dsysprof=disabled -Dtests=false -Ddocs=disabled'''

[pipeline.compile]
script = '''
cd source/libsoup-${VERSION}
meson compile -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/libsoup-${VERSION}
DESTDIR=${STAGING_DIR} meson install -C build'''

[[output]]
runtime_deps = ['brotli', 'glib-networking', 'glib', 'libpsl', 'libxml2', 'nghttp2', 'sqlite']
