name = "cpio"
version = "2.15"
release = 1
description = "GNU tool for managing archives of files"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/cpio/"

link_deps = ['glibc']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/cpio/cpio-${VERSION}.tar.gz"
extract_to = "source"

[[sources]]
type = "local"
sha256 = "SKIP"
path = "patches/c23-conformity.patch"

[pipeline.prepare]
script = '''
cd source/cpio-${VERSION}
patch -Np1 -i ${WORKDIR}/${NAME}-c23-conformity.patch'''

[pipeline.configure]
script = '''
cd source/cpio-${VERSION}
./configure --prefix=/usr --with-rmt=/dev/null'''

[pipeline.compile]
script = '''
cd source/cpio-${VERSION}
make -j$(nproc)'''

[pipeline.check]
script = '''
cd source/cpio-${VERSION}
make check'''

[pipeline.staging]
script = '''
cd source/cpio-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['glibc']
