name = "cpio"
version = "2.15"
release = 1
description = "GNU tool for managing archives of files"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/cpio/"

[dependencies]
link = ["glibc"]

[[sources]]
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/cpio/cpio-${VERSION}.tar.gz"
extract_to = "source"

[[sources]]
sha256 = "SKIP"
type = "local"
path = "patches/cpio-2.15-c23-conformity.patch"

[lifecycle.prepare]
script = '''
cd source
patch -Np1 -i ${WORKDIR}/cpio-2.15-c23-conformity.patch'''

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr --with-rmt=/dev/null'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc) -C ${WORKDIR}'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install -C ${WORKDIR}'''
