name = "nano"
version = "8.6"
release = 1
description = "A small, simple text editor aiming to replace Pico"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.nano-editor.org/"

[dependencies]
build = ["gcc", "make"]
link = ["ncurses"]

[[sources]]
uri = "https://www.nano-editor.org/dist/v8/nano-${VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr \
--sysconfdir=/etc \
--enable-utf8 \
--docdir=/usr/share/doc/nano-${VERSION}

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install
install -v -m644 doc/{nano.html,sample.nanorc} ${PART_DIR}/usr/share/doc/nano-${VERSION}

'''

[lifecycle.fabricate]
