name = "sphinxcontrib-htmlhelp"
version = "2.1.0"
release = 1
description = "Sphinx extension for HTML help output"
license = "BSD-2-Clause"
arch = "x86_64"
url = "https://github.com/sphinx-doc/sphinxcontrib-htmlhelp"

[dependencies]
runtime = ["python"]
build = ["python", "flit-core"]

[[sources]]
uri = "https://pypi.org/packages/source/s/sphinxcontrib_htmlhelp/sphinxcontrib_htmlhelp-${VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .

'''

[lifecycle.fabricate]
