name = "gettext"
version = "1.0"
release = 1
description = "Utilities for internationalization and localization"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/gettext/"

[dependencies]
build = ["gcc", "make"]

[[sources]]
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/gettext/gettext-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/gettext-${VERSION}'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install
chmod -v 0755 ${PART_DIR}/usr/lib/preloadable_libintl.so'''
