name = "libidn2"
version = "2.3.7"
release = 1
description = "Library for internationalized domain names (IDNA2008/TR46)"
license = "LGPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/libidn/#libidn2"

[dependencies]
build = ["gcc", "make"]
link = ["libunistring"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/libidn/libidn2-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr --disable-static'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
