name = "adwaita-icon-theme"
version = "50.0"
release = 1
description = "Adwaita icon theme"
license = "LGPL-3.0-or-later"
arch = "any"
url = "https://gitlab.gnome.org/GNOME/adwaita-icon-theme"


build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/adwaita-icon-theme/50/adwaita-icon-theme-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/adwaita-icon-theme-${VERSION}
meson setup build --prefix=/usr --buildtype=release'''

[pipeline.compile]
script = '''
cd source/adwaita-icon-theme-${VERSION}
meson compile -C build'''

[pipeline.staging]
script = '''
cd source/adwaita-icon-theme-${VERSION}
meson install -C build --destdir ${STAGING_DIR}'''

[[output]]
runtime_deps = ['hicolor-icon-theme']

[output.hooks]
post_install = '''
gtk-update-icon-cache -qtf /usr/share/icons/Adwaita 2>/dev/null || true
gtk-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || true

'''
post_upgrade = '''
gtk-update-icon-cache -qtf /usr/share/icons/Adwaita 2>/dev/null || true
gtk-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || true

'''
