[plan]
name = "iso-codes"
version = "4.17.0"
release = 1
description = "Lists of country, language and currency names"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://salsa.debian.org/iso-codes-team/iso-codes"

[dependencies]
build = ["python"]

[[sources]]
uri = "https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v${PART_VERSION}/iso-codes-v${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr
'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install
'''
