name = "iso-codes"
version = "4.17.0"
release = 1
description = "Lists of country, language and currency names"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://salsa.debian.org/iso-codes-team/iso-codes"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v${VERSION}/iso-codes-v${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/iso-codes-v${VERSION}
./configure --prefix=/usr'''

[pipeline.compile]
script = '''
cd source/iso-codes-v${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/iso-codes-v${VERSION}
make DESTDIR=${STAGING_DIR} install'''
