name = "iso-codes"
version = "4.17.0"
release = 1
description = "Lists of country, language and currency names"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://salsa.debian.org/iso-codes-team/iso-codes"

[dependencies]
build = ["python"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v${VERSION}/iso-codes-v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
