name = "intel-compute-runtime"
version = "26.09.37435.1"
release = 1
description = "Intel(R) Graphics Compute Runtime for oneAPI Level Zero and OpenCL(TM) Driver"
license = "MIT"
arch = "x86_64"
url = "https://github.com/intel/compute-runtime"

[dependencies]
runtime = ["glibc", "intel-gmmlib", "intel-graphics-compiler", "libgcc", "libstdc++"]
build = ["cmake", "ninja", "igsc", "level-zero-headers", "libva", "pkg-config"]

[[sources]]
type = "http"
url = "https://github.com/intel/compute-runtime/archive/${VERSION}/intel-compute-runtime-${VERSION}.tar.gz"
sha256 = "8c51e99af2971f5e6e662b7dd47b786e50da0252323ce4abaa8d135fe3f3f294"

[options]
ccache = true

[lifecycle.configure]
script = '''
# 修复 Blender 等应用中的运行时错误
export CFLAGS="${CFLAGS} -DSANITIZER_BUILD=1"
export CXXFLAGS="${CXXFLAGS} -DSANITIZER_BUILD=1"

# 修正 _FORTIFY_SOURCE 重定义警告
export CFLAGS="${CFLAGS/-Wp,-D_FORTIFY_SOURCE=?/}"
export CXXFLAGS="${CXXFLAGS/-Wp,-D_FORTIFY_SOURCE=?/}"

# 使用源码树自带的 OpenCL 头文件
_opencl_headers_dir="${WORKDIR}/compute-runtime-${VERSION}/third_party/opencl_headers"
export CXXFLAGS="${CXXFLAGS} -isystem ${_opencl_headers_dir}"

# 解析版本号组件
MAJOR="${VERSION%%.*}"
MINOR="$(echo $VERSION | cut -d . -f2)"
BUILD="$(echo $VERSION | cut -d . -f3)"

cmake -B build -S "compute-runtime-${VERSION}" \
    -GNinja \
    -DCMAKE_BUILD_TYPE='Release' \
    -DCMAKE_INSTALL_LIBDIR='lib' \
    -DCMAKE_INSTALL_PREFIX='/usr' \
    -DNEO_BUILD_UNVERSIONED_OCLOC='ON' \
    -DNEO_DISABLE_LD_GOLD:BOOL='ON' \
    -DNEO_DISABLE_WERROR:BOOL='ON' \
    -DNEO_OCL_VERSION_MAJOR="$MAJOR" \
    -DNEO_OCL_VERSION_MINOR="$MINOR" \
    -DNEO_VERSION_BUILD="$BUILD" \
    -DKHRONOS_GL_HEADERS_DIR='/usr/include' \
    -DKHRONOS_HEADERS_DIR="$_opencl_headers_dir" \
    -Wno-dev
'''

[lifecycle.compile]
script = "cmake --build build -j$(nproc)"

[lifecycle.staging]
script = '''
DESTDIR=${PART_DIR} cmake --install build
install -D -m644 "compute-runtime-${VERSION}/LICENSE.md" -t "${PART_DIR}/usr/share/licenses/${NAME}"

# 补全 Level Zero 驱动的软链接
cd ${PART_DIR}/usr/lib
target_so=$(find . -regex '.*libze_intel_gpu.so.[0-9]*' -exec basename {} \;)
if [ -n "$target_so" ]; then
    ln -s "$target_so" "libze_intel_gpu.so"
fi
'''

[output]
provides = ["level-zero-driver", "opencl-driver"]
