name = "c-ares"
version = "1.34.6"
release = 1
description = "Asynchronous DNS requests and name resolution library"
license = "MIT"
arch = "x86_64"
url = "https://c-ares.org/"

[dependencies]
build = ["gcc", "make"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/c-ares/c-ares/releases/download/v${VERSION}/c-ares-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr --disable-static'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
