name = "gnome-desktop"
version = "44.5"
release = 1
description = "Library with common API for various GNOME modules"
license = "LGPL-2.1-or-later AND GPL-2.0-or-later"
arch = "x86_64"
url = "https://gitlab.gnome.org/GNOME/gnome-desktop"

link_deps = ['glib', 'gtk4', 'libseccomp', 'libxkbcommon']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/gnome-desktop/44/gnome-desktop-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/gnome-desktop-${VERSION}
meson setup build --prefix=/usr --buildtype=release -Dintrospection=true -Dgtk_doc=false -Ddesktop_docs=false -Ddebug_tools=false -Dlegacy_library=false'''

[pipeline.compile]
script = '''
cd source/gnome-desktop-${VERSION}
ninja -C build'''

[pipeline.staging]
script = '''
cd source/gnome-desktop-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[hooks]
post_install = "glib-compile-schemas /usr/share/glib-2.0/schemas 2>/dev/null || true"
post_upgrade = "glib-compile-schemas /usr/share/glib-2.0/schemas 2>/dev/null || true"

[[output]]
runtime_deps = ['gsettings-desktop-schemas', 'iso-codes', 'glib', 'gtk4', 'libseccomp', 'libxkbcommon']
