name = "prudence"
version = "0.0.1"
release = 1
description = "Rust CLI for moving files and directories into the XDG trash"
license = "NOASSERTION"
arch = "x86_64"
url = "https://github.com/ming2k/prudence"

[dependencies]
build = ["rust"]

[[sources]]
type = "http"
sha256 = "eb16564fda7542cbc10a007f842a6ac4f4097210155a629d1757f9e1f31d58ea"
url = "https://github.com/ming2k/prudence/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.compile]
isolation = "relaxed"
env = { CARGO_HOME = '${BUILD_DIR}/.cargo', CARGO_TARGET_DIR = '${BUILD_DIR}/target' }
script = '''
cd source
cargo build --release --locked'''

[lifecycle.staging]
script = '''
cd source
install -Dm755 target/release/prudence ${PART_DIR}/usr/bin/prudence
install -Dm644 man/man1/prudence.1 ${PART_DIR}/usr/share/man/man1/prudence.1'''

