name = "iproute2"
version = "6.19.0"
release = 1
description = "Programs for basic and advanced IPV4-based networking"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://wiki.linuxfoundation.org/networking/iproute2"

[dependencies]
build = ["gcc", "make"]

[[sources]]
uri = "https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-${PART_VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.prepare]
script = '''
cd ${BUILD_DIR}
sed -i /ARPD/d Makefile
rm -fv man/man8/arpd.8

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make NETNS_RUN_DIR=/run/netns -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make SBINDIR=/usr/bin DESTDIR=${PART_DIR} install

'''

[lifecycle.fabricate]
