name = "vim"
version = "9.2.0043"
release = 2
description = "Vi Improved, a highly configurable text editor"
license = "custom:vim"
arch = "x86_64"
url = "https://www.vim.org"

[dependencies]
build = [
    "gcc",
    "autoconf",
    "make",
    "pkgconf",
]
link = ["acl", "ncurses", "zlib"]

[[sources]]
uri = "https://github.com/vim/vim/archive/v${PART_VERSION}/vim-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.prepare]
script = '''
# Allow VIMRCLOC to override the compiled-in vimrc paths at install time
sed -E 's|^.*(#define SYS_.*VIMRC_FILE.*").*$|\1|g' -i ${BUILD_DIR}/src/feature.h
sed -E 's|^.*(#define VIMRC_FILE.*").*$|\1|g' -i ${BUILD_DIR}/src/feature.h
(cd ${BUILD_DIR}/src && autoconf)

'''

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure \
  --prefix=/usr \
  --localstatedir=/var/lib/vim \
  --with-features=huge \
  --with-x=no \
  --disable-gui \
  --disable-gpm \
  --enable-multibyte \
  --enable-cscope \
  --enable-acl \
  --enable-python3interp=dynamic \
  --enable-luainterp=dynamic \
  --enable-perlinterp=dynamic \
  --enable-rubyinterp=dynamic \
  --enable-tclinterp=dynamic \
  --disable-canberra

'''

[lifecycle.compile]
script = "make -j$(nproc) -C ${BUILD_DIR}"

[lifecycle.staging]
script = '''
make -j1 -C ${BUILD_DIR} VIMRCLOC=/etc DESTDIR=${PART_DIR} install

# Remove files traditionally provided by (n)vi
rm -f ${PART_DIR}/usr/bin/{ex,view}
find ${PART_DIR}/usr/share/man -name 'ex.1' -o -name 'view.1' -o -name 'evim.1' \
  -delete

install -Dm644 ${BUILD_DIR}/runtime/doc/uganda.txt \
  ${PART_DIR}/usr/share/licenses/vim/license.txt

'''

[lifecycle.fabricate]
