name = "sassc"
version = "3.6.2"
release = 1
description = "Command line driver for libsass"
license = "MIT"
arch = "x86_64"
url = "https://github.com/sass/sassc"

[dependencies]
build = [
    "autoconf",
    "automake",
    "gcc",
    "libtool",
    "make",
]
link = ["libsass"]

[[sources]]
uri = "https://github.com/sass/sassc/archive/${PART_VERSION}/sassc-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
autoreconf -fi
./configure --prefix=/usr

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install

'''
