name = "dejagnu"
version = "1.6.3"
release = 1
description = "Framework for testing other programs"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/dejagnu/"

[dependencies]
runtime = ["expect"]
build = ["expect", "make", "texinfo"]

[[sources]]
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/dejagnu/dejagnu-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
mkdir -v build
cd build
../configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source/build
makeinfo --html --no-split -o doc/dejagnu.html ../doc/dejagnu.texi
makeinfo --plaintext       -o doc/dejagnu.txt  ../doc/dejagnu.texi'''

[lifecycle.check]
script = '''
cd source/build
make check'''

[lifecycle.staging]
script = '''
cd source/build
make DESTDIR=${PART_DIR} install
install -v -dm755  ${PART_DIR}/usr/share/doc/dejagnu-1.6.3
install -v -m644   doc/dejagnu.{html,txt} ${PART_DIR}/usr/share/doc/dejagnu-1.6.3'''
