name = "dav1d"
version = "1.5.3"
release = 1
description = "Fastest AV1 decoder on all platforms"
license = "BSD-2-Clause"
arch = "x86_64"

[dependencies]
build = ["meson", "ninja", "nasm", "gcc"]

[[sources]]
type = "http"
sha256 = "cbe212b02faf8c6eed5b6d55ef8a6e363aaab83f15112e960701a9c3df813686"
url = "https://code.videolan.org/videolan/dav1d/-/archive/${VERSION}/dav1d-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = "cd source && meson setup build --prefix=/usr --buildtype=release"

[lifecycle.compile]
script = '''
cd source
meson compile -C ${WORKDIR}/build'''

[lifecycle.staging]
script = '''
cd source
meson install -C ${WORKDIR}/build --destdir ${PART_DIR}'''
