name = "swig"
version = "4.4.1"
release = 1
description = "Simplified Wrapper and Interface Generator"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://swig.org"

link_deps = ['pcre2', 'zlib']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/swig/swig/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.prepare]
script = '''
cd source/swig-${VERSION}
./autogen.sh'''

[lifecycle.configure]
script = '''
cd source/swig-${VERSION}
./configure --prefix=/usr \
            --with-pcre2'''

[lifecycle.compile]
script = '''
cd source/swig-${VERSION}
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/swig-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['pcre2', 'zlib']
