name = "python-distro"
version = "1.9.0"
release = 1
description = "OS platform information API"
license = "Apache-2.0"
arch = "x86_64"
url = "https://github.com/python-distro/distro"

[dependencies]
runtime = ["python"]
build = ["python", "setuptools"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://pypi.org/packages/source/d/distro/distro-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source/distro-${VERSION}
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .'''
