name = "gdb"
version = "15.2"
release = 1
description = "The GNU Debugger"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/gdb/"

[dependencies]
build = ["gcc", "make", "texinfo"]
link = ["expat", "glibc", "mpfr", "ncurses", "readline", "xz", "zlib"]
runtime = ["expat", "ncurses", "python", "readline", "xz", "zlib"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/gdb/gdb-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.prepare]
script = '''
cd source
mkdir -v build'''

[lifecycle.configure]
script = '''
cd source/build
../configure --prefix=/usr \
    --with-system-readline \
    --with-python=/usr/bin/python3 \
    --with-system-zlib \
    --with-expat \
    --with-lzma \
    --enable-tui \
    --disable-multilib \
    --disable-werror'''

[lifecycle.compile]
script = '''
cd source/build
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/build
make DESTDIR=${PART_DIR} install

# Remove static libraries
rm -f ${PART_DIR}/usr/lib/libinproctrace.a'''
