name = "python-babel"
version = "2.18.0"
release = 1
description = "Internationalization utilities for Python"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://babel.pocoo.org/"

[dependencies]
runtime = ["python"]
build = ["python", "setuptools"]

[[sources]]
uri = "https://pypi.org/packages/source/b/babel/babel-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .

'''
