[plan]
name = "gperf"
version = "3.3"
release = 1
description = "Perfect hash function generator"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/gperf/"

[dependencies]
build = ["gcc", "make"]
[sources]
uris = ["https://ftp.gnu.org/gnu/gperf/gperf-3.3.tar.gz"]
sha256 = ["SKIP"]

[lifecycle.configure]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.3
'''

[lifecycle.compile]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
'''

[lifecycle.package]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PKG_DIR} install
'''
