name = "libassuan"
version = "3.0.2"
release = 1
description = "IPC library for GnuPG"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://gnupg.org/software/libassuan/"

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://gnupg.org/ftp/gcrypt/libassuan/libassuan-${VERSION}.tar.bz2"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libassuan-${VERSION}
./configure --prefix=/usr --disable-static'''

[pipeline.compile]
script = '''
cd source/libassuan-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/libassuan-${VERSION}
DESTDIR=${STAGING_DIR} make install'''
