name = "qrcodegen"
version = "1.8.0"
release = 1
description = "QR Code generator library for C and C++"
license = "MIT"
arch = "x86_64"
url = "https://www.nayuki.io/page/qr-code-generator-library"

[dependencies]
build = ["gcc", "make"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/nayuki/QR-Code-generator/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.compile]
script = '''
cd source/c
gcc -c -O2 -fPIC -o qrcodegen.o qrcodegen.c
gcc -shared -o libqrcodegen.so qrcodegen.o

cd source/cpp
g++ -c -O2 -fPIC -std=c++17 -o qrcodegen.o qrcodegen.cpp
g++ -shared -o libqrcodegencpp.so qrcodegen.o'''

[lifecycle.staging]
script = '''
cd source
install -Dm755 ${WORKDIR}/c/libqrcodegen.so ${PART_DIR}/usr/lib/libqrcodegen.so
install -Dm644 ${WORKDIR}/c/qrcodegen.h ${PART_DIR}/usr/include/qrcodegen.h

install -Dm755 ${WORKDIR}/cpp/libqrcodegencpp.so ${PART_DIR}/usr/lib/libqrcodegencpp.so
install -Dm644 ${WORKDIR}/cpp/qrcodegen.hpp ${PART_DIR}/usr/include/qrcodegen.hpp'''
