name = "libglvnd"
version = "1.7.0"
release = 1
description = "The GL Vendor-Neutral Dispatch library"
license = "MIT"
arch = "x86_64"


build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v1.7.0/libglvnd-v1.7.0.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/libglvnd-v${VERSION}
meson setup build --prefix=/usr --libdir=lib -Dglx=disabled -Dx11=disabled -Dheaders=true'''

[lifecycle.compile]
script = '''
ninja -C source/libglvnd-v${VERSION}/build -j$(nproc)'''

[lifecycle.staging]
script = '''
DESTDIR=${STAGING_DIR} ninja -C source/libglvnd-v${VERSION}/build install'''

