name = "jq"
version = "1.8.1"
release = 2
description = "Command-line JSON processor"
license = "MIT"
arch = "x86_64"
url = "https://jqlang.org/"


[[sources]]
type = "http"
sha256 = "2be64e7129cecb11d5906290eba10af694fb9e3e7f9fc208a311dc33ca837eb0"
url = "https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-1.8.1.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/jq-${VERSION}
./configure --prefix=/usr --disable-static --with-oniguruma=builtin'''

[pipeline.compile]
script = '''
cd source/jq-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/jq-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

