name = "gpgme"
version = "2.0.1"
release = 2
description = "GnuPG Made Easy"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://gnupg.org/software/gpgme/"

[dependencies]
build = ["gcc", "make", "pkgconf"]
link = ["libassuan", "libgpg-error", "gnupg"]

[[sources]]
uri = "https://gnupg.org/ftp/gcrypt/gpgme/gpgme-${VERSION}.tar.bz2"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure \
    --prefix=/usr \
    --disable-static \
    --disable-gpg-test

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
DESTDIR=${PART_DIR} make install

'''

[lifecycle.fabricate]
