name = "strace"
version = "6.19"
release = 1
description = "Diagnostic, debugging and instructional userspace tracer"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://strace.io"

[dependencies]
build = ["gcc", "make"]
link = ["glibc"]

[[sources]]
sha256 = "SKIP"
url = "https://github.com/strace/strace/releases/download/v${VERSION}/strace-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr \
    --with-libiberty'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc) -C ${WORKDIR}'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
