name = "libtiff"
version = "4.7.1"
release = 1
description = "TIFF image format library"
license = "libtiff"
arch = "x86_64"
url = "https://libtiff.gitlab.io/libtiff/"

link_deps = ['zlib', 'libjpeg-turbo']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.osgeo.org/libtiff/tiff-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/tiff-${VERSION}
./configure --prefix=/usr --disable-static --disable-docs'''

[lifecycle.compile]
script = '''
cd source/tiff-${VERSION}
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/tiff-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['zlib', 'libjpeg-turbo']
