name = "uthash"
version = "2.3.0"
release = 1
description = "Hash table macros for C structures"
license = "BSD-1-Clause"
arch = "x86_64"
url = "https://troydhanson.github.io/uthash/"

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/troydhanson/uthash/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source
install -d ${PART_DIR}/usr/include
install -m644 ${WORKDIR}/src/*.h ${PART_DIR}/usr/include/'''
