name = "tree-sitter"
version = "0.24.7"
release = 1
description = "An incremental parsing system for programming tools"
license = "MIT"
arch = "x86_64"
url = "https://tree-sitter.github.io/tree-sitter/"

[dependencies]
build = ["gcc", "make"]

[[sources]]
uri = "https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc) PREFIX=/usr

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make PREFIX=/usr DESTDIR=${PART_DIR} install

'''
