[plan]
name = "wayland-protocols"
version = "1.47"
release = 2
description = "Specifications of extended Wayland protocols"
license = "MIT"
arch = "any"

[dependencies]
build = ["meson", "ninja", "pkgconf", "wayland"]
link = ["wayland"]

[[sources]]
uri = "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/${PART_VERSION}/downloads/wayland-protocols-${PART_VERSION}.tar.xz"
sha256 = "5fd4349bcbc9bab9a46f8cf77d1f434296a7a052c87440a094f63fcf62a58e20"

[lifecycle.configure]
script = "cd ${BUILD_DIR} && meson setup build --prefix=/usr -Dtests=false"

[lifecycle.compile]
script = "cd ${BUILD_DIR} && meson compile -C build"

[lifecycle.staging]
script = "cd ${BUILD_DIR} && meson install -C build --destdir ${PART_DIR}"
