name = "bc"
version = "7.0.3"
release = 1
description = "Arbitrary precision numeric processing language and calculator"
license = "BSD-2-Clause"
arch = "x86_64"
url = "https://github.com/gavinhoward/bc"

[dependencies]
build = ["gcc", "make"]
link = ["readline"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/gavinhoward/bc/releases/download/${VERSION}/bc-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
CC='gcc -std=c99' ./configure --prefix=/usr -G -O3 -r'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.check]
script = '''
cd source
make test'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install
rm -f ${PART_DIR}/usr/share/info/dir'''
