name = "bc"
version = "7.0.3"
release = 1
description = "Arbitrary precision numeric processing language and calculator"
license = "BSD-2-Clause"
arch = "x86_64"
url = "https://github.com/gavinhoward/bc"

link_deps = ['readline']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/gavinhoward/bc/releases/download/${VERSION}/bc-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/bc-${VERSION}
CC='gcc -std=c99' ./configure --prefix=/usr -G -O3 -r'''

[lifecycle.compile]
script = '''
cd source/bc-${VERSION}
make -j$(nproc)'''

[lifecycle.check]
script = '''
cd source/bc-${VERSION}
make test'''

[lifecycle.staging]
script = '''
cd source/bc-${VERSION}
make DESTDIR=${STAGING_DIR} install
rm -f ${STAGING_DIR}/usr/share/info/dir'''

[[output]]
runtime_deps = ['readline']
