name = "tree-sitter-cli"
version = "0.26.8"
release = 1
description = "CLI tool for developing, testing, and using Tree-sitter parsers"
license = "MIT"
arch = "x86_64"
url = "https://github.com/tree-sitter/tree-sitter"

[dependencies]
build = ["gcc", "rust"]
link = ["gcc", "glibc"]

[[sources]]
sha256 = "e6826b7533ec3a885aba598377a6d20b5a6321ff3db76968e960c2352d3a5077"
url = "https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.compile]
dockyard = "relaxed"
script = '''
cd source
cargo build --release --locked -p tree-sitter-cli'''

[lifecycle.staging]
script = '''
cd source
install -Dm755 target/release/tree-sitter ${PART_DIR}/usr/bin/tree-sitter'''
