name = "lz4"
version = "1.10.0"
release = 1
description = "Extremely fast lossless compression algorithm"
license = "BSD-2-Clause AND GPL-2.0-only"
arch = "x86_64"
url = "https://lz4.github.io/lz4/"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/lz4/lz4/releases/download/v${VERSION}/lz4-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.compile]
script = '''
cd source/lz4-${VERSION}
make BUILD_STATIC=no PREFIX=/usr -j$(nproc)'''

[lifecycle.check]
script = '''
cd source/lz4-${VERSION}
make -j1 check'''

[lifecycle.staging]
script = '''
cd source/lz4-${VERSION}
make BUILD_STATIC=no PREFIX=/usr DESTDIR=${STAGING_DIR} install'''

