name = "hyphen"
version = "2.8.8"
release = 1
description = "A hyphenation library"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "http://hunspell.sourceforge.net/"

[dependencies]
build = ["gawk", "gcc", "make", "patch"]
link = ["glibc"]

[[sources]]
sha256 = "SKIP"
url = "http://deb.debian.org/debian/pool/main/h/hyphen/hyphen_${VERSION}.orig.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source
make'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
