name = "ocl-icd"
version = "2025.07.22"
release = 2
description = "OpenCL ICD Loader (official Khronos implementation)"
license = "Apache-2.0"
arch = "x86_64"
url = "https://github.com/KhronosGroup/OpenCL-ICD-Loader"

link_deps = ['glibc']
build_deps = ['ninja', 'cmake']

[[sources]]
type = "http"
url = "https://github.com/KhronosGroup/OpenCL-ICD-Loader/archive/refs/tags/v${VERSION}/OpenCL-ICD-Loader-${VERSION}.tar.gz"
sha256 = "SKIP"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/ocl-icd-${VERSION}
cmake -B build -G Ninja -S OpenCL-ICD-Loader-* -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DOPENCL_ICD_LOADER_HEADERS_DIR=/usr/include'''

[pipeline.compile]
script = '''
cd source/ocl-icd-${VERSION}
ninja -C build'''

[pipeline.staging]
script = '''
cd source/ocl-icd-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['glibc']
provides = ["libOpenCL", "opencl-loader"]

[hooks]
post_install = "ldconfig"
post_upgrade = "ldconfig"
