name = "cava"
version = "0.10.7"
release = 1
description = "Console-based audio visualizer for ALSA, PipeWire, PulseAudio and more"
license = "MIT"
arch = "x86_64"
url = "https://github.com/karlstav/cava"

link_deps = ['fftw', 'iniparser', 'alsa-lib', 'pipewire', 'ncurses']
build_deps = ['autoconf', 'automake', 'libtool']

[[sources]]
type = "http"
sha256 = "43f994f7e609fab843af868d8a7bc21471ac62c5a4724ef97693201eac42e70a"
url = "https://github.com/karlstav/cava/archive/refs/tags/${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.prepare]
script = '''
cd source/cava-${VERSION}
autoreconf -vfi'''

[lifecycle.configure]
script = '''
cd source/cava-${VERSION}
./configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source/cava-${VERSION}
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/cava-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['alsa-lib', 'pipewire', 'ncurses', 'fftw', 'iniparser']
backup = ["/etc/cava/config"]
