name = "python-sphinx"
version = "9.1.0"
release = 1
description = "Python documentation generator"
license = "BSD-2-Clause"
arch = "x86_64"
url = "https://www.sphinx-doc.org/"

[dependencies]
runtime = ["python", "python-jinja2", "python-pygments", "python-docutils", "python-babel", "python-alabaster", "python-requests", "python-packaging", "sphinxcontrib-applehelp", "sphinxcontrib-devhelp", "sphinxcontrib-htmlhelp", "sphinxcontrib-jsmath", "sphinxcontrib-qthelp", "sphinxcontrib-serializinghtml"]
build = ["python", "flit-core"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://pypi.org/packages/source/s/sphinx/sphinx-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .'''
