name = "python-idna"
version = "3.11"
release = 1
description = "Internationalized Domain Names in Applications (IDNA)"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://github.com/kjd/idna"

[dependencies]
runtime = ["python"]
build = ["python", "flit-core"]

[[sources]]
sha256 = "SKIP"
url = "https://pypi.org/packages/source/i/idna/idna-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .'''
