name = "libjxl"
version = "0.11.2"
release = 1
description = "JPEG XL image format reference implementation"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://github.com/libjxl/libjxl"

link_deps = ['brotli', 'hwy', 'lcms2', 'libjpeg-turbo', 'libpng']
build_deps = ['ninja', 'cmake']

[[sources]]
type = "http"
sha256 = "ab38928f7f6248e2a98cc184956021acb927b16a0dee71b4d260dc040a4320ea"
url = "https://github.com/libjxl/libjxl/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/libjxl-${VERSION}
cmake -B build -G Ninja \
  -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ \
  -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_TESTING=OFF \
  -DJPEGXL_ENABLE_BENCHMARK=OFF \
  -DJPEGXL_ENABLE_EXAMPLES=OFF \
  -DJPEGXL_ENABLE_TESTS=OFF \
  -DJPEGXL_FORCE_SYSTEM_BROTLI=ON \
  -DJPEGXL_FORCE_SYSTEM_HWY=ON \
  -DJPEGXL_FORCE_SYSTEM_LCMS2=ON \
  -DJPEGXL_ENABLE_SKCMS=OFF \
  -DJPEGXL_ENABLE_SJPEG=OFF \
  -DJPEGXL_BUNDLE_LIBPNG=OFF \
  -DJPEGXL_ENABLE_JPEGLI=OFF'''

[lifecycle.compile]
script = '''
cd source/libjxl-${VERSION}
ninja -C build'''

[lifecycle.staging]
script = '''
cd source/libjxl-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['brotli', 'hwy', 'lcms2', 'libjpeg-turbo', 'libpng']
