name = "libxml2"
version = "2.15.3"
release = 1
description = "XML C parser and toolkit"
license = "MIT"
arch = "x86_64"
url = "https://gitlab.gnome.org/GNOME/libxml2"


build_deps = ['meson', 'ninja', 'python']

[[sources]]
type = "http"
sha256 = "78262a6e7ac170d6528ebfe2efccdf220191a5af6a6cd61ea4a9a9a5042c7a07"
url = "https://download.gnome.org/sources/libxml2/2.15/libxml2-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libxml2-${VERSION}
mkdir -p build && cd build
meson setup .. --prefix=/usr \
    -D history=enabled \
    -D icu=enabled \
    -D python=enabled \
    -D docs=disabled'''

[pipeline.compile]
script = '''
cd source/libxml2-${VERSION}/build
ninja -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/libxml2-${VERSION}/build
DESTDIR=${STAGING_DIR} ninja install'''

[[output]]
runtime_deps = ['icu', 'python']
