name = "libsecret"
version = "0.21.7"
release = 1
description = "Library for storing and retrieving passwords and other secrets"
license = "LGPL-2.1-or-later"
arch = "x86_64"

[dependencies]
build = ["gettext", "glib", "gobject-introspection", "meson", "ninja", "pkgconf"]
link = ["glib", "libgcrypt"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/libsecret/0.21/libsecret-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build --prefix=/usr --buildtype=release -Dvapi=false -Dgtk_doc=false -Dmanpage=false -Dcrypto=libgcrypt'''

[lifecycle.compile]
script = '''
cd source
meson compile -C ${WORKDIR}/build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} meson install -C ${WORKDIR}/build'''
