name = "libsecret"
version = "0.21.7"
release = 1
description = "Library for storing and retrieving passwords and other secrets"
license = "LGPL-2.1-or-later"
arch = "x86_64"

link_deps = ['glib', 'libgcrypt']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/libsecret/0.21/libsecret-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libsecret-${VERSION}
meson setup build --prefix=/usr --buildtype=release -Dvapi=false -Dgtk_doc=false -Dmanpage=false -Dcrypto=libgcrypt'''

[pipeline.compile]
script = '''
cd source/libsecret-${VERSION}
meson compile -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/libsecret-${VERSION}
DESTDIR=${STAGING_DIR} meson install -C build'''

[[output]]
runtime_deps = ['glib', 'libgcrypt']
