name = "fcft"
version = "3.3.1"
release = 1
description = "Simple library for font loading and glyph rasterization"
license = "MIT"
arch = "x86_64"
url = "https://codeberg.org/dnkl/fcft"

build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://codeberg.org/dnkl/fcft/archive/${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/fcft
meson setup build \
--prefix=/usr          \
--buildtype=release    \
-D docs=disabled'''

[pipeline.compile]
script = '''
cd source/fcft
ninja -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/fcft
DESTDIR=${STAGING_DIR} ninja -C build install'''
