name = "fcft"
version = "3.3.1"
release = 1
description = "Simple library for font loading and glyph rasterization"
license = "MIT"
arch = "x86_64"
url = "https://codeberg.org/dnkl/fcft"

[[sources]]
uri = "https://codeberg.org/dnkl/fcft/archive/${VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
meson setup ${BUILD_DIR}/build ${BUILD_DIR} \
--prefix=/usr          \
--buildtype=release    \
-D docs=disabled

'''

[lifecycle.compile]
script = "ninja -C ${BUILD_DIR}/build -j$(nproc)"

[lifecycle.staging]
script = "DESTDIR=${PART_DIR} ninja -C ${BUILD_DIR}/build install"

[lifecycle.fabricate]
