name = "openssl"
version = "3.6.2"
release = 1
description = "Management tools and libraries relating to cryptography"
license = "Apache-2.0"
arch = "x86_64"
url = "https://www.openssl.org/"

[dependencies]
build = ["gcc", "make", "perl"]
link = ["zlib"]

[[sources]]
sha256 = "SKIP"
url = "https://github.com/openssl/openssl/releases/download/openssl-${VERSION}/openssl-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./config --prefix=/usr         \
         --openssldir=/etc/ssl \
         --libdir=lib          \
         shared                \
         zlib-dynamic'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile
make MANSUFFIX=ssl DESTDIR=${PART_DIR} install
mv -v ${PART_DIR}/usr/share/doc/openssl ${PART_DIR}/usr/share/doc/openssl-${VERSION}'''
