name = "vala"
version = "0.56.19"
release = 1
description = "Programming language and compiler that generates GObject-based C code"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://gitlab.gnome.org/GNOME/vala"

[dependencies]
build = ["bison", "flex", "meson", "ninja", "pkgconf"]
link = ["glib"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/vala/0.56/vala-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr --disable-valadoc'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
