name = "nghttp2"
version = "1.68.1"
release = 1
description = "HTTP/2 C Library and tools"
license = "MIT"
arch = "x86_64"
url = "https://nghttp2.org/"

[dependencies]
build = ["gcc", "make"]

[[sources]]
uri = "https://github.com/nghttp2/nghttp2/releases/download/v${VERSION}/nghttp2-${VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr     \
--disable-static  \
--enable-lib-only \
--docdir=/usr/share/doc/nghttp2-${VERSION}

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install

'''

[lifecycle.fabricate]
