name = "nghttp2"
version = "1.68.1"
release = 1
description = "HTTP/2 C Library and tools"
license = "MIT"
arch = "x86_64"
url = "https://nghttp2.org/"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/nghttp2/nghttp2/releases/download/v${VERSION}/nghttp2-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/nghttp2-${VERSION}
./configure --prefix=/usr     \
--disable-static  \
--enable-lib-only \
--docdir=/usr/share/doc/nghttp2-${VERSION}'''

[pipeline.compile]
script = '''
cd source/nghttp2-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/nghttp2-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

