name = "python-pygments"
version = "2.20.0"
release = 1
description = "Python syntax highlighter"
license = "BSD-2-Clause"
arch = "x86_64"
url = "https://pygments.org/"

[dependencies]
runtime = ["python"]
build = ["python", "hatchling"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://pypi.org/packages/source/p/pygments/pygments-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .'''
