name = "python-pygments"
version = "2.19.2"
release = 1
description = "Python syntax highlighter"
license = "BSD-2-Clause"
arch = "x86_64"
url = "https://pygments.org/"

[dependencies]
runtime = ["python"]
build = ["python", "hatchling"]

[[sources]]
uri = "https://pypi.org/packages/source/p/pygments/pygments-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .

'''

[lifecycle.fabricate]
