name = "yaml-cpp"
version = "yaml-cpp-0.9.0"
release = 1
description = "YAML parser and emitter in C++"
license = "MIT"
arch = "x86_64"
url = "https://github.com/jbeder/yaml-cpp"


build_deps = ['ninja', 'cmake']

[[sources]]
type = "http"
sha256 = "25cb043240f828a8c51beb830569634bc7ac603978e0f69d6b63558dadefd49a"
url = "https://github.com/jbeder/yaml-cpp/archive/refs/tags/${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/yaml-cpp-${VERSION}
cmake -B build -G Ninja \
    -DCMAKE_CXX_FLAGS="-include cstdint" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DYAML_CPP_BUILD_TESTS=OFF \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5'''

[pipeline.compile]
script = '''
cd source/yaml-cpp-${VERSION}
ninja -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/yaml-cpp-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

