name = "libtool"
version = "2.5.4"
release = 1
description = "GNU generic library support script"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/libtool/"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://mirrors.kernel.org/gnu/libtool/libtool-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libtool-${VERSION}
./configure --prefix=/usr'''

[pipeline.compile]
script = '''
cd source/libtool-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/libtool-${VERSION}
make DESTDIR=${STAGING_DIR} install
rm -fv ${STAGING_DIR}/usr/lib/libltdl.a'''

