name = "libdrm"
version = "2.4.131"
release = 1
description = "Direct Rendering Manager library"
license = "MIT"
arch = "x86_64"
url = "https://dri.freedesktop.org/libdrm/"


build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://dri.freedesktop.org/libdrm/libdrm-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libdrm-${VERSION}
meson setup build \
--prefix=/usr          \
--buildtype=release    \
-D udev=true           \
-D valgrind=disabled'''

[pipeline.compile]
script = '''
cd source/libdrm-${VERSION}
ninja -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/libdrm-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

