[plan]
name = "libdrm"
version = "2.4.131"
release = 1
description = "Direct Rendering Manager library"
license = "MIT"
arch = "x86_64"
url = "https://dri.freedesktop.org/libdrm/"

[dependencies]
build = ["meson", "ninja"]

[[sources]]
uri = "https://dri.freedesktop.org/libdrm/libdrm-${PKG_VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
meson setup ${BUILD_DIR}/build ${BUILD_DIR} \
--prefix=/usr          \
--buildtype=release    \
-D udev=true           \
-D valgrind=disabled
'''

[lifecycle.compile]
script = "ninja -C ${BUILD_DIR}/build -j$(nproc)"

[lifecycle.staging]
script = "DESTDIR=${PKG_DIR} ninja -C ${BUILD_DIR}/build install"
