[plan]
name = "flit-core"
version = "3.12.0"
release = 1
description = "PEP 517 build backend for packages using Flit"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://flit.pypa.io/"

[dependencies]
build = ["python"]
[sources]
uris = ["https://pypi.org/packages/source/f/flit_core/flit_core-${PKG_VERSION}.tar.gz"]
sha256 = ["SKIP"]

[lifecycle.package]
script = '''
cd ${BUILD_DIR}
pip3 install --no-index --no-user --no-deps --root=${PKG_DIR} --no-build-isolation .
'''
