name = "mpv"
version = "0.41.0"
release = 2
description = "A free, open source, and cross-platform media player"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://mpv.io"

link_deps = ['alsa-lib', 'ffmpeg', 'lcms2', 'libass', 'libdrm', 'libplacebo', 'libva', 'luajit', 'mesa', 'pipewire', 'vulkan-loader', 'wayland', 'libxkbcommon']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/mpv-player/mpv/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/mpv-${VERSION}
meson setup build \
--prefix=/usr \
--buildtype=release \
-D libmpv=true \
-D cdda=disabled \
-D drm=enabled \
-D libarchive=disabled \
-D dvdnav=disabled \
-D javascript=disabled \
-D lua=luajit \
-D uchardet=disabled \
-D tests=false \
-D alsa=enabled \
-D pipewire=enabled \
-D vulkan=enabled \
-D wayland=enabled \
-D gl=enabled'''

[lifecycle.compile]
script = '''
cd source/mpv-${VERSION}
ninja -C build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/mpv-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['alsa-lib', 'ffmpeg', 'lcms2', 'libass', 'libdrm', 'libplacebo', 'libva', 'luajit', 'mesa', 'pipewire', 'vulkan-loader', 'wayland', 'libxkbcommon']
