name = "pcre2"
version = "10.47"
release = 2
description = "Perl-compatible regular expression library"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://www.pcre.org/"

[dependencies]
build = ["bash", "gcc", "make"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-${VERSION}/pcre2-${VERSION}.tar.bz2"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr --disable-static --enable-unicode --enable-pcre2-16 --enable-pcre2-32'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
