name = "pcre2"
version = "10.45"
release = 1
description = "Perl-compatible regular expression library"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://www.pcre.org/"

[dependencies]
build = ["bash", "gcc", "make"]

[[sources]]
uri = "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-${PART_VERSION}/pcre2-${PART_VERSION}.tar.bz2"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr --disable-static --enable-unicode

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install

'''
