name = "shared-mime-info"
version = "2.4"
release = 1
description = "Shared MIME info database"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://gitlab.freedesktop.org/xdg/shared-mime-info"

link_deps = ['glib', 'libxml2']
build_deps = ['gettext', 'meson', 'ninja', 'pkgconf']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/${VERSION}/shared-mime-info-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/shared-mime-info-${VERSION}
sed -i '/^if xmlto\.found()/,/^endif$/d' data/meson.build
meson setup build \
    --prefix=/usr          \
    --buildtype=release    \
    -D update-mimedb=false \
    -D build-tests=false'''

[lifecycle.compile]
script = '''
cd source/shared-mime-info-${VERSION}
ninja -C build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/shared-mime-info-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['glib', 'libxml2']

[output.hooks]
post_install = "update-mime-database /usr/share/mime 2>/dev/null || true"
post_upgrade = "update-mime-database /usr/share/mime 2>/dev/null || true"
