[plan]
name = "file"
version = "5.46"
release = 1
description = "Utility for determining the type of a given file using magic number recognition"
license = "BSD-2-Clause"
arch = "x86_64"
url = "https://www.darwinsys.com/file/"

[dependencies]
build = ["gcc", "make"]
[sources]
uris = ["https://astron.com/pub/file/file-${PKG_VERSION}.tar.gz"]
sha256 = ["SKIP"]

[lifecycle.configure]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr
'''

[lifecycle.compile]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
'''

[lifecycle.check]
dockyard = "none"
optional = true
script = '''
cd ${BUILD_DIR}
make check
'''

[lifecycle.package]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PKG_DIR} install
'''
