name = "file"
version = "5.47"
release = 1
description = "Utility for determining the type of a given file using magic number recognition"
license = "BSD-2-Clause"
arch = "x86_64"
url = "https://www.darwinsys.com/file/"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://astron.com/pub/file/file-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/file-${VERSION}
./configure --prefix=/usr'''

[pipeline.compile]
script = '''
cd source/file-${VERSION}
make -j$(nproc)'''

[pipeline.check]
script = '''
cd source/file-${VERSION}
make check'''

[pipeline.staging]
script = '''
cd source/file-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

