name = "crun"
version = "1.27"
release = 1
description = "Fast OCI container runtime"
license = "GPL-2.0-or-later AND LGPL-2.1-or-later"
arch = "x86_64"
url = "https://github.com/containers/crun"

[dependencies]
build = ["gcc", "make", "pkgconf", "python"]
runtime = ["glibc", "libcap", "libseccomp", "systemd"]
link = ["glibc", "libcap", "libseccomp", "systemd"]

[[sources]]
sha256 = "99077cc701a9f6842f70384eb05e9429da1ad338cdef3e0bac5a486cbf2ca75d"
url = "https://github.com/containers/crun/releases/download/${VERSION}/crun-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
dockyard = "none"
env = {'ac_cv_path_MD2MAN': ''}
script = '''
cd source/crun-${VERSION}
./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --disable-libcrun \
    --without-python-bindings \
    --enable-embedded-yajl'''

[lifecycle.compile]
dockyard = "none"
script = '''
cd source/crun-${VERSION}
make -j$(nproc)'''

[lifecycle.staging]
dockyard = "none"
script = '''
cd source/crun-${VERSION}
make DESTDIR=${PART_DIR} install'''
