name = "binutils"
version = "2.46.0"
release = 1
description = "A set of programs to assemble and manipulate binary and object files"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/binutils/"

[dependencies]
build = ["gcc", "make"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/binutils/binutils-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
mkdir -v build
cd       build
../configure --prefix=/usr       \
--sysconfdir=/etc   \
--enable-gold       \
--enable-ld=default \
--enable-plugins    \
--enable-shared     \
--disable-werror    \
--enable-64-bit-bfd \
--enable-new-dtags  \
--without-zlib      \
--without-zstd      \
--enable-default-hash-style=gnu'''

[lifecycle.compile]
script = '''
cd source/build
make tooldir=/usr'''

[lifecycle.staging]
script = '''
cd source/build
make DESTDIR=${PART_DIR} tooldir=/usr install

# Remove static libraries
rm -fv ${PART_DIR}/usr/lib/lib{bfd,ctf,ctf-nobfd,gprofng,opcodes,sframe}.a'''

[hooks]
post_install = '''
# Clean old binutils residuals
rm -f /usr/lib/libbfd-2.45.so /usr/lib/libbfd-2.44.so /usr/lib/libbfd-2.43.1.so
rm -f /usr/lib/libsframe.so.1.0.0
ldconfig

'''
post_upgrade = "ldconfig"
