name = "glycin"
version = "2.1.1"
release = 1
description = "Sandboxed image decoding library (Full Format Support)"
license = "MPL-2.0 OR LGPL-2.1-or-later"
arch = "x86_64"
url = "https://gitlab.gnome.org/GNOME/glycin"

[dependencies]
runtime = ["bubblewrap"]
build = ["meson", "ninja", "pkgconf", "rust", "libseccomp"]
link = ["glib", "gtk4", "lcms2", "fontconfig", "libjpeg-turbo", "libpng", "libheif", "libjxl", "librsvg"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/glycin/2.1/glycin-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
isolation = "relaxed"
script = '''
cd source
meson setup build --prefix=/usr --buildtype=release -Dtests=false -Dvapi=false'''

[lifecycle.compile]
isolation = "relaxed"
script = '''
cd source
meson compile -C ${WORKDIR}/build'''

[lifecycle.staging]
script = '''
cd source
meson install -C ${WORKDIR}/build --destdir ${PART_DIR}'''
