name = "glycin"
version = "2.0.8"
release = 1
description = "Sandboxed image decoding library (Full Format Support)"
license = "MPL-2.0 OR LGPL-2.1-or-later"
arch = "x86_64"
url = "https://gitlab.gnome.org/GNOME/glycin"

[dependencies]
runtime = ["bubblewrap"]
build = [
    "meson",
    "ninja",
    "pkgconf",
    "rust",
    "libseccomp",
]
link = [
    "glib",
    "gtk4",
    "lcms2",
    "fontconfig",
    "libjpeg-turbo",
    "libpng",
    "libheif",
    "libjxl",
    "librsvg",
]

[[sources]]
uri = "https://download.gnome.org/sources/glycin/2.0/glycin-${PART_VERSION}.tar.xz"
sha256 = "6b9aef4f626bf969dfd04b563b83d521271a30c3d6df6a6a8463fd55490891df"

[lifecycle.configure]
dockyard = "relaxed"
script = '''
cd ${BUILD_DIR}
meson setup build --prefix=/usr --buildtype=release -Dtests=false -Dvapi=false

'''

[lifecycle.compile]
dockyard = "relaxed"
script = "meson compile -C ${BUILD_DIR}/build"

[lifecycle.staging]
script = "meson install -C ${BUILD_DIR}/build --destdir ${PART_DIR}"

[lifecycle.fabricate]
