name = "libxslt"
version = "1.1.45"
release = 1
description = "XSLT C library for transforming XML"
license = "MIT"
arch = "x86_64"
url = "https://gitlab.gnome.org/GNOME/libxslt"

[dependencies]
build = ["gcc", "make"]
link = ["libxml2"]

[[sources]]
sha256 = "SKIP"
url = "https://download.gnome.org/sources/libxslt/1.1/libxslt-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr                 \
--disable-static              \
--docdir=/usr/share/doc/libxslt-${VERSION}'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
