name = "libxslt"
version = "1.1.45"
release = 1
description = "XSLT C library for transforming XML"
license = "MIT"
arch = "x86_64"
url = "https://gitlab.gnome.org/GNOME/libxslt"

link_deps = ['libxml2']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/libxslt/1.1/libxslt-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libxslt-${VERSION}
./configure --prefix=/usr                 \
--disable-static              \
--docdir=/usr/share/doc/libxslt-${VERSION}'''

[pipeline.compile]
script = '''
cd source/libxslt-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/libxslt-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['libxml2']
