name = "wayland-utils"
version = "1.3.0"
release = 2
description = "Wayland diagnostic utilities (wayland-info)"
license = "MIT"
arch = "x86_64"
url = "https://gitlab.freedesktop.org/wayland/wayland-utils"

[dependencies]
runtime = ["wayland"]
build = ["gcc", "libdrm", "meson", "ninja", "pkgconf", "wayland"]
link = ["glibc"]

[[sources]]
sha256 = "SKIP"
url = "https://gitlab.freedesktop.org/wayland/wayland-utils/-/archive/${VERSION}/wayland-utils-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build \
    --prefix=/usr \
    --buildtype=release \
    -D drm=enabled'''

[lifecycle.compile]
script = '''
cd source
ninja -C ${WORKDIR}/build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} ninja -C ${WORKDIR}/build install'''
