name = "libcap"
version = "2.76"
release = 3
description = "POSIX 1003.1e capabilities userspace interface"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://sites.google.com/site/fullycapable/"

[dependencies]
build = ["gcc", "make"]

[[sources]]
sha256 = "SKIP"
url = "https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.prepare]
script = '''
cd source
sed -i '/install -m.*STA/d' libcap/Makefile'''

[lifecycle.compile]
script = '''
cd source
make prefix=/usr lib=lib SBINDIR=/usr/bin -j$(nproc)'''

[lifecycle.check]
script = '''
cd source
make test'''

[lifecycle.staging]
script = '''
cd source
make prefix=/usr lib=lib SBINDIR=/usr/bin DESTDIR=${PART_DIR} install'''
