[plan]
name = "libcap"
version = "2.76"
release = 1
description = "POSIX 1003.1e capabilities userspace interface"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://sites.google.com/site/fullycapable/"

[dependencies]
build = ["gcc", "make"]
[sources]
uris = ["https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-${PKG_VERSION}.tar.xz"]
sha256 = ["SKIP"]

[lifecycle.prepare]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
sed -i '/install -m.*STA/d' libcap/Makefile
'''

[lifecycle.compile]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make prefix=/usr lib=lib
'''

[lifecycle.check]
dockyard = "none"
optional = true
script = '''
cd ${BUILD_DIR}
make test
'''

[lifecycle.package]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make prefix=/usr lib=lib DESTDIR=${PKG_DIR} install
'''
