name = "python-pycairo"
version = "1.29.0"
release = 1
description = "Python bindings for cairo"
license = "LGPL-2.1-only OR MPL-1.1"
arch = "x86_64"
url = "https://pycairo.readthedocs.io/"

link_deps = ['cairo']
build_deps = ['python']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://pypi.org/packages/source/p/pycairo/pycairo-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.staging]
script = '''
cd source/pycairo-${VERSION}
pip3 install --no-index --no-user --no-deps --ignore-installed --root=${STAGING_DIR} --no-build-isolation .'''

[[output]]
runtime_deps = ['python', 'cairo']
