name = "libnotify"
version = "0.8.8"
release = 1
description = "Library for sending desktop notifications"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://gnome.pages.gitlab.gnome.org/libnotify/"

link_deps = ['glib', 'gdk-pixbuf']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "23420ef619dc2cb5aebad613f4823a2fa41c07e5a1d05628d40f6ec4b35bfddd"
url = "https://download.gnome.org/sources/libnotify/0.8/libnotify-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/libnotify-${VERSION}
meson setup build --prefix=/usr --buildtype=release -Dtests=false -Dintrospection=enabled -Dman=false -Dgtk_doc=false -Ddocbook_docs=disabled'''

[lifecycle.compile]
script = '''
cd source/libnotify-${VERSION}
meson compile -C build'''

[lifecycle.staging]
script = '''
cd source/libnotify-${VERSION}
meson install -C build --destdir ${STAGING_DIR}'''

[[output]]
runtime_deps = ['glib', 'gdk-pixbuf']
