name = "fmt"
version = "12.1.0"
release = 1
description = "Fast and safe alternative to C stdio and C++ iostreams"
license = "MIT"
arch = "x86_64"
url = "https://fmt.dev/"


build_deps = ['ninja', 'cmake']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/fmtlib/fmt/archive/refs/tags/${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/fmt-${VERSION}
cmake -B build -G Ninja \
  -DCMAKE_BUILD_TYPE=None \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DBUILD_SHARED_LIBS=ON \
  -DFMT_DOC=OFF \
  -DFMT_TEST=OFF'''

[pipeline.compile]
script = '''
cd source/fmt-${VERSION}
ninja -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/fmt-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

