name = "catatonit"
version = "0.2.1"
release = 1
description = "Minimal container init process"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://github.com/openSUSE/catatonit"

link_deps = ['glibc']
build_deps = ['autoconf', 'automake', 'libtool']

[[sources]]
type = "http"
sha256 = "9950425501af862e12f618bdc930ea755c46db6a16072a1462b4fc93b2bd59bc"
url = "https://github.com/openSUSE/catatonit/releases/download/v${VERSION}/catatonit.tar.xz"
extract_to = "source"

[pipeline.prepare]
isolation = "none"
script = '''
cd source/catatonit-${VERSION}
sed -i 's/ -all-static//' Makefile.am
autoreconf -fi'''

[pipeline.configure]
isolation = "none"
script = '''
cd source/catatonit-${VERSION}
./configure --prefix=/usr --bindir=/usr/bin'''

[pipeline.compile]
isolation = "none"
script = '''
cd source/catatonit-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
isolation = "none"
script = '''
cd source/catatonit-${VERSION}
make DESTDIR=${STAGING_DIR} install
install -dm755 ${STAGING_DIR}/usr/libexec/podman
ln -sf ../../bin/catatonit ${STAGING_DIR}/usr/libexec/podman/catatonit'''

[[output]]
runtime_deps = ['glibc']
