[plan]
name = "mpfr"
version = "4.2.2"
release = 1
description = "C library for multiple-precision floating-point computations"
license = "LGPL-3.0-or-later"
arch = "x86_64"
url = "https://www.mpfr.org/"

[dependencies]
build = ["make"]
link = ["gmp"]

[[sources]]
uri = "https://ftp.gnu.org/gnu/mpfr/mpfr-${PKG_VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr        \
--disable-static     \
--enable-thread-safe \
--docdir=/usr/share/doc/mpfr-4.2.2
'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
make html
'''

[lifecycle.check]
script = '''
cd ${BUILD_DIR}
make check
'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PKG_DIR} install
make DESTDIR=${PKG_DIR} install-html
'''
