name = "libepoxy"
version = "1.5.10"
release = 2
description = "Library for handling OpenGL function pointer management"
license = "MIT"
arch = "x86_64"
url = "https://github.com/anholt/libepoxy"

[dependencies]
runtime = ["mesa"]
build = ["meson", "ninja", "pkgconf"]
link = ["mesa", "libglvnd"]

[[sources]]
sha256 = "SKIP"
url = "https://download.gnome.org/sources/libepoxy/1.5/libepoxy-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build \
--prefix=/usr       \
--buildtype=release \
-D x11=false'''

[lifecycle.compile]
script = '''
cd source
meson compile -C ${WORKDIR}/build'''

[lifecycle.staging]
script = '''
cd source
meson install -C ${WORKDIR}/build --destdir ${PART_DIR}'''
