name = "libepoxy"
version = "1.5.10"
release = 2
description = "Library for handling OpenGL function pointer management"
license = "MIT"
arch = "x86_64"
url = "https://github.com/anholt/libepoxy"

link_deps = ['mesa', 'libglvnd']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/libepoxy/1.5/libepoxy-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libepoxy-${VERSION}
meson setup build \
--prefix=/usr       \
--buildtype=release \
-D x11=false'''

[pipeline.compile]
script = '''
cd source/libepoxy-${VERSION}
meson compile -C build'''

[pipeline.staging]
script = '''
cd source/libepoxy-${VERSION}
meson install -C build --destdir ${STAGING_DIR}'''

[[output]]
runtime_deps = ['mesa', 'libglvnd']
