[plan]
name = "hatchling"
version = "1.29.0"
release = 1
description = "Modern, extensible Python build backend"
license = "MIT"
arch = "x86_64"
url = "https://hatch.pypa.io/"

[dependencies]
runtime = [
    "python",
    "python-packaging",
    "python-pathspec",
    "python-pluggy",
    "python-trove-classifiers",
]
build = ["python"]

[[sources]]
uri = "https://pypi.org/packages/source/h/hatchling/hatchling-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .
'''
