name = "polkit-gnome"
version = "0.105"
release = 2
description = "Legacy polkit authentication agent for GNOME"
license = "LGPL-2.0-or-later"
arch = "x86_64"
url = "https://gitlab.gnome.org/Archive/polkit-gnome"

[dependencies]
runtime = ["polkit"]
build = [
    "gcc",
    "intltool",
    "make",
    "pkgconf",
]
link = ["glib", "gtk3"]

[[sources]]
uri = "https://download.gnome.org/sources/polkit-gnome/0.105/polkit-gnome-${PART_VERSION}.tar.xz"
sha256 = "SKIP"

[[sources]]
uri = "polkit-gnome-authentication-agent-1.desktop"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr --libexecdir=/usr/lib/polkit-gnome

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install
install -Dm644 ${FILES_DIR}/polkit-gnome-authentication-agent-1.desktop ${PART_DIR}/etc/xdg/autostart/polkit-gnome-authentication-agent-1.desktop

'''

[lifecycle.fabricate]
