name = "hatch-vcs"
version = "0.5.0"
release = 1
description = "Hatch plugin for versioning from VCS (git/hg) tags"
license = "MIT"
arch = "x86_64"
url = "https://github.com/ofek/hatch-vcs"


build_deps = ['python']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://pypi.org/packages/source/h/hatch_vcs/hatch_vcs-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.staging]
script = '''
cd source/hatch-vcs-${VERSION}
pip3 install --no-index --no-user --no-deps --ignore-installed --root=${STAGING_DIR} --no-build-isolation .'''

[[output]]
runtime_deps = ['python', 'hatchling', 'setuptools-scm']
