name = "qt6-multimedia"
version = "6.11.0"
release = 1
description = "Qt 6 multimedia module"
license = "LGPL-3.0-only"
arch = "x86_64"
url = "https://www.qt.io"

[dependencies]
runtime = ["qt6-base", "ffmpeg", "pipewire"]
build = ["cmake", "gcc", "ninja", "pkgconf", "qt6-base", "ffmpeg", "pipewire"]
link = ["ffmpeg", "pipewire", "qt6-base"]

[[sources]]
type = "http"
sha256 = "90c4cac0a7a983b68d1b0873d0714e7873b9a493403fa8593e8a4eea3ea26040"
url = "https://download.qt.io/official_releases/qt/6.11/6.11.0/submodules/qtmultimedia-everywhere-src-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
cmake -B build -G Ninja \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DBUILD_TESTING=OFF \
    -DQT_BUILD_EXAMPLES=OFF \
    -DQT_BUILD_TESTS=OFF'''

[lifecycle.compile]
script = '''
cd source
ninja -j$(nproc) -C build'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} ninja -C build install'''
