name = "autoconf"
version = "2.72"
release = 1
description = "Package for producing shell scripts that automatically configure software"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/autoconf/"

[dependencies]
build = ["m4", "make", "perl"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/autoconf/autoconf-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
