name = "wget"
version = "1.25.0"
release = 1
description = "Network utility to retrieve files from the web"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/wget/"

link_deps = ['openssl:default', 'libidn2:default', 'libpsl:default', 'pcre2:default', 'zlib:default']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/wget/wget-${VERSION}.tar.lz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr      \
    --sysconfdir=/etc          \
    --with-ssl=openssl'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${STAGING_DIR} install'''

[output]
runtime_deps = ['ca-certificates:default']
