name = "wget"
version = "1.25.0"
release = 2
description = "Network utility to retrieve files from the web"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/wget/"

link_deps = ['openssl', 'libidn2', 'libpsl', 'pcre2', 'zlib']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/wget/wget-${VERSION}.tar.lz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/wget-${VERSION}
./configure --prefix=/usr      \
    --sysconfdir=/etc          \
    --with-ssl=openssl'''

[pipeline.compile]
script = '''
cd source/wget-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/wget-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['ca-certificates', 'openssl', 'libidn2', 'libpsl', 'pcre2', 'zlib']
