name = "libsndfile"
version = "1.2.2"
release = 1
description = "C library for reading and writing sound files"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://libsndfile.github.io/libsndfile/"

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/libsndfile/libsndfile/releases/download/${VERSION}/libsndfile-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
CFLAGS="-std=gnu17" ./configure --prefix=/usr --disable-static'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} make install'''
