name = "gnupg"
version = "2.4.9"
release = 1
description = "GNU Privacy Guard"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://gnupg.org"

[dependencies]
runtime = ["pinentry"]
link = [
    "libgcrypt",
    "libgpg-error",
    "libassuan",
    "libksba",
    "npth",
    "readline",
    "gnutls",
    "sqlite",
]

[[sources]]
uri = "https://gnupg.org/ftp/gcrypt/gnupg/gnupg-${VERSION}.tar.bz2"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr              \
--libexecdir=/usr/lib/gnupg \
--sbindir=/usr/bin          \
--sysconfdir=/etc           \
--enable-keyboxd            \
--enable-large-secmem       \
--disable-ldap              \
--disable-doc

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc) LDFLAGS="${LDFLAGS} -lreadline -lhistory"

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
DESTDIR=${PART_DIR} make install
ln -sf gpg  ${PART_DIR}/usr/bin/gpg2
ln -sf gpgv ${PART_DIR}/usr/bin/gpgv2

'''

[lifecycle.fabricate]
