name = "fuse-overlayfs"
version = "1.16"
release = 1
description = "FUSE implementation of overlay+shiftfs for rootless containers"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://github.com/containers/fuse-overlayfs"

[dependencies]
build = ["autoconf", "automake", "pkgconf"]
link = ["libfuse3"]

[[sources]]
uri = "https://github.com/containers/fuse-overlayfs/archive/refs/tags/v${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
autoreconf -fi
./configure --prefix=/usr

'''

[lifecycle.compile]
script = "make -j$(nproc) -C ${BUILD_DIR}"

[lifecycle.staging]
script = "make DESTDIR=${PART_DIR} install -C ${BUILD_DIR}"

[lifecycle.fabricate]
