name = "libportal"
version = "0.10.0"
release = 1
description = "GIO-style async APIs for Flatpak Portals"
license = "LGPL-3.0-or-later"
arch = "x86_64"
url = "https://github.com/flatpak/libportal"

link_deps = ['glib', 'gtk4']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "1c74a3f7becbd4ff745d7f565afd06e97e50eb080a0e268cb14bb55289a745bf"
url = "https://github.com/flatpak/libportal/releases/download/${VERSION}/libportal-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libportal-${VERSION}
meson setup build --prefix=/usr --buildtype=release -Dbackend-gtk3=disabled -Dbackend-gtk4=enabled -Dintrospection=true -Dvapi=false -Ddocs=false -Dtests=false'''

[pipeline.compile]
script = '''
cd source/libportal-${VERSION}
meson compile -C build'''

[pipeline.staging]
script = '''
cd source/libportal-${VERSION}
meson install -C build --destdir ${STAGING_DIR}'''

[[output]]
runtime_deps = ['glib', 'gtk4']
