name = "python-urllib3"
version = "2.6.3"
release = 1
description = "HTTP library with thread-safe connection pooling and file post support"
license = "MIT"
arch = "x86_64"
url = "https://urllib3.readthedocs.io/"

[dependencies]
runtime = ["python"]
build = ["python", "hatchling", "hatch-vcs"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/urllib3/urllib3/archive/${VERSION}/python-urllib3-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source
SETUPTOOLS_SCM_PRETEND_VERSION=${VERSION} pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .'''
