name = "dust"
version = "1.2.4"
release = 1
description = "A more intuitive version of du in rust"
license = "Apache-2.0"
arch = "x86_64"
url = "https://github.com/bootandy/dust"

[dependencies]
build = ["rust"]

[[sources]]
uri = "https://github.com/bootandy/dust/archive/refs/tags/v${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.compile]
dockyard = "relaxed"
env = { CARGO_HOME = "${BUILD_DIR}/.cargo", CARGO_TARGET_DIR = "${BUILD_DIR}/target" }
script = '''
cd ${BUILD_DIR}
cargo build --release --locked
'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
install -Dm755 target/release/dust ${PART_DIR}/usr/bin/dust
'''

[lifecycle.fabricate]
