name = "linux-firmware"
version = "20260410"
release = 1
description = "Firmware files for Linux"
license = "GPL-2.0-only AND GPL-2.0-or-later AND custom"
arch = "any"
url = "https://gitlab.com/kernel-firmware/linux-firmware"

[[sources]]
uri = "https://cdn.kernel.org/pub/linux/kernel/firmware/linux-firmware-${VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
mkdir -p ${PART_DIR}/usr/lib/firmware
./copy-firmware.sh ${PART_DIR}/usr/lib/firmware
'''

[lifecycle.fabricate]
