name = "rust"
version = "1.94.1"
release = 1
description = "The Rust programming language compiler and standard library"
license = "Apache-2.0 AND MIT"
arch = "x86_64"
url = "https://www.rust-lang.org"

[dependencies]
runtime = ["gcc"]
link = ["glibc"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://static.rust-lang.org/dist/rust-${VERSION}-x86_64-unknown-linux-gnu.tar.xz"
extract_to = "source"

[lifecycle.compile]
script = '''
cd source
./install.sh --destdir=${PART_DIR} --prefix=/usr --without=rust-docs'''

[output]

[output."cargo"]
include = ["/.*"]
description = "Cargo package manager for Rust"
[output."cargo".dependencies]
runtime = ["rust"]
