name = "libnl"
version = "3.11.0"
release = 1
description = "Library for dealing with netlink sockets"
license = "LGPL-2.1-only"
arch = "x86_64"
url = "https://github.com/thom311/libnl"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/thom311/libnl/releases/download/libnl3_11_0/libnl-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libnl-${VERSION}
./configure --prefix=/usr     \
--sysconfdir=/etc \
--disable-static'''

[pipeline.compile]
script = '''
cd source/libnl-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/libnl-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

