name = "libnl"
version = "3.11.0"
release = 1
description = "Library for dealing with netlink sockets"
license = "LGPL-2.1-only"
arch = "x86_64"
url = "https://github.com/thom311/libnl"

[dependencies]
build = ["gcc", "make"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/thom311/libnl/releases/download/libnl3_11_0/libnl-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr     \
--sysconfdir=/etc \
--disable-static'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
