[plan]
name = "libnl"
version = "3.11.0"
release = 1
description = "Library for dealing with netlink sockets"
license = "LGPL-2.1-only"
arch = "x86_64"
url = "https://github.com/thom311/libnl"

[dependencies]
build = ["gcc", "make"]
[sources]
uris = ["https://github.com/thom311/libnl/releases/download/libnl3_11_0/libnl-${PKG_VERSION}.tar.gz"]
sha256 = ["SKIP"]

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr     \
--sysconfdir=/etc \
--disable-static
'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
'''

[lifecycle.package]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PKG_DIR} install
'''
