name = "qt6-wayland"
version = "6.11.0"
release = 1
description = "Qt 6 Wayland platform plugin"
license = "LGPL-3.0-only"
arch = "x86_64"
url = "https://www.qt.io"

link_deps = ['wayland', 'qt6-base', 'qt6-declarative']
build_deps = ['ninja', 'cmake']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.qt.io/official_releases/qt/6.11/6.11.0/submodules/qtwayland-everywhere-src-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/qtwayland-everywhere-src-${VERSION}
cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release'''

[pipeline.compile]
script = '''
cd source/qtwayland-everywhere-src-${VERSION}
ninja -j$(nproc) -C build'''

[pipeline.staging]
script = '''
cd source/qtwayland-everywhere-src-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['wayland', 'qt6-base', 'qt6-declarative']
