name = "libedit"
version = "20251016-3.1"
release = 1
description = "BSD-style command line editing library"
license = "BSD-3-Clause"
arch = "x86_64"

[dependencies]
build = ["gcc", "make"]
link = ["ncurses"]

[[sources]]
uri = "https://thrysoee.dk/editline/libedit-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install

'''

[lifecycle.fabricate]
