name = "swtpm"
version = "0.10.1"
release = 1
description = "Libtpms-based TPM emulator for QEMU and other hypervisors"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://github.com/stefanberger/swtpm"

link_deps = ['glib:default', 'gmp:default', 'json-glib:default', 'libtpms:default', 'openssl:default']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/stefanberger/swtpm/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./autogen.sh --prefix=/usr --disable-static --without-cuse --without-selinux --without-seccomp --disable-tests'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${STAGING_DIR} install'''

[output]
runtime_deps = ['libtpms:default']
