[plan]
name = "psmisc"
version = "23.7"
release = 1
description = "Programs for displaying information about running processes"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://gitlab.com/psmisc/psmisc"

[dependencies]
build = ["gcc", "make"]
link = ["ncurses"]
[sources]
uris = ["https://downloads.sourceforge.net/project/psmisc/psmisc/psmisc-${PKG_VERSION}.tar.xz"]
sha256 = ["SKIP"]

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr
'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
'''

[lifecycle.package]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PKG_DIR} install
'''
