name = "attr"
version = "2.5.2"
release = 1
description = "Utilities to administer the extended attributes of filesystem objects"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://savannah.nongnu.org/projects/attr"

[dependencies]
build = ["gcc", "make"]

[[sources]]
sha256 = "SKIP"
url = "https://download.savannah.gnu.org/releases/attr/attr-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr     \
--disable-static  \
--sysconfdir=/etc \
--docdir=/usr/share/doc/attr-2.5.2'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.check]
script = '''
cd source
make check'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
