name = "attr"
version = "2.5.2"
release = 1
description = "Utilities to administer the extended attributes of filesystem objects"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://savannah.nongnu.org/projects/attr"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.savannah.gnu.org/releases/attr/attr-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/attr-${VERSION}
./configure --prefix=/usr     \
--disable-static  \
--sysconfdir=/etc \
--docdir=/usr/share/doc/attr-2.5.2'''

[pipeline.compile]
script = '''
cd source/attr-${VERSION}
make -j$(nproc)'''

[pipeline.check]
script = '''
cd source/attr-${VERSION}
make check'''

[pipeline.staging]
script = '''
cd source/attr-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

