name = "sudo"
version = "1.9.17p2"
release = 4
description = "Give certain users the ability to run some commands as root"
license = "ISC"
arch = "x86_64"
url = "https://www.sudo.ws"

[dependencies]
build = ["gcc", "make"]
link = ["glibc", "linux-pam"]

[[sources]]
uri = "https://www.sudo.ws/dist/sudo-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr \
--libexecdir=/usr/lib \
--sbindir=/usr/bin \
--with-rundir=/run/sudo \
--with-vardir=/var/db/sudo \
--with-logfac=auth \
--with-pam \
--with-env-editor \
--with-all-insults \
--with-secure-path-value=/usr/local/sbin:/usr/local/bin:/usr/bin \
--enable-tmpfiles.d \
--docdir=/usr/share/doc/sudo-${PART_VERSION} \
--with-passprompt="[sudo] password for %p: "

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install
mkdir -p ${PART_DIR}/etc/sudoers.d
install -vdm755 ${PART_DIR}/etc/pam.d

cat > ${PART_DIR}/etc/pam.d/sudo << 'PAMEOF'
# Begin /etc/pam.d/sudo
auth      include     system-auth
account   include     system-account
session   include     system-session
# End /etc/pam.d/sudo
PAMEOF

cat > ${PART_DIR}/etc/pam.d/sudo-i << 'PAMEOF'
# Begin /etc/pam.d/sudo-i
auth      include     sudo
account   include     sudo
session   include     sudo
# End /etc/pam.d/sudo-i
PAMEOF

'''

[output]
backup = ["/etc/sudoers", "/etc/pam.d/sudo", "/etc/pam.d/sudo-i"]
