name = "tllist"
version = "1.1.0"
release = 1
description = "Typed linked list C header library"
license = "MIT"
arch = "x86_64"
url = "https://codeberg.org/dnkl/tllist"

build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://codeberg.org/dnkl/tllist/archive/1.1.0.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/tllist-${VERSION}
meson setup build \
--prefix=/usr          \
--buildtype=release'''

[lifecycle.compile]
script = '''
cd source/tllist-${VERSION}
ninja -C build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/tllist-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''
