name = "dtc"
version = "1.7.2"
release = 1
description = "Device Tree Compiler and libfdt library"
license = "GPL-2.0-or-later OR BSD-2-Clause"
arch = "x86_64"
url = "https://www.kernel.org/pub/software/utils/dtc/"

[dependencies]
build = ["bash", "gcc", "make", "pkgconf", "flex", "bison"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://www.kernel.org/pub/software/utils/dtc/dtc-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.compile]
script = '''
cd source
make -j$(nproc) NO_PYTHON=1 PREFIX=/usr CFLAGS="${CFLAGS} -std=gnu17"'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} NO_PYTHON=1 PREFIX=/usr CFLAGS="${CFLAGS} -std=gnu17" install'''
