name = "jansson"
version = "2.14.1"
release = 1
description = "C library for encoding, decoding and manipulating JSON data"
license = "MIT"
arch = "x86_64"
url = "https://sourceforge.net/projects/jansson/"

[dependencies]
build = ["gcc", "make"]
link = ["glibc"]

[[sources]]
sha256 = "SKIP"
url = "https://github.com/akheron/jansson/releases/download/v${VERSION}/jansson-${VERSION}.tar.bz2"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr --disable-static'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.check]
script = '''
cd source
make check'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
