name = "xapian-core"
version = "2.0.0"
release = 1
description = "Probabilistic information retrieval library"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://xapian.org/"

[dependencies]
build = ["gcc", "make", "pkgconf"]
link = ["libuuid", "zlib"]

[[sources]]
sha256 = "6cea3f49952a47224439a40bdb3608f928d121ad8721b9921cc42802d548ecf8"
url = "https://oligarchy.co.uk/xapian/${VERSION}/xapian-core-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr --disable-static'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
