name = "freetype"
version = "2.13.3"
release = 1
description = "Font rendering library"
license = "FTL OR GPL-2.0-or-later"
arch = "x86_64"
url = "https://freetype.org"

[[sources]]
sha256 = "SKIP"
url = "https://download.savannah.gnu.org/releases/freetype/freetype-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
sed -ri "s:.*(AUX_MODULES.*valid):\1:" modules.cfg
sed -r "s:.*(#.*SUBPIXEL_RENDERING) .*:\1:" \
-i include/freetype/config/ftoption.h
./configure --prefix=/usr     \
--enable-freetype-config \
--disable-static'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} make install'''
