name = "libevent"
version = "2.1.12-stable"
release = 2
description = "An event notification library for developing asynchronous applications"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://libevent.org/"

link_deps = ['openssl']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/libevent/libevent/releases/download/release-${VERSION}/libevent-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/libevent-${VERSION}
./configure --prefix=/usr --disable-static'''

[pipeline.compile]
script = '''
cd source/libevent-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/libevent-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['openssl']
