name = "glib-networking"
version = "2.80.1"
release = 2
description = "Network extensions for GLib"
license = "LGPL-2.1-or-later"
arch = "x86_64"

link_deps = ['glib']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/glib-networking/2.80/glib-networking-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
env = { GIO_MODULE_DIR = '/usr/lib/gio/modules' }
script = '''
cd source/glib-networking-${VERSION}
meson setup build --prefix=/usr --buildtype=release -Dgnutls=enabled -Dlibproxy=enabled -Dopenssl=disabled'''

[pipeline.compile]
script = '''
cd source/glib-networking-${VERSION}
meson compile -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/glib-networking-${VERSION}
DESTDIR=${STAGING_DIR} meson install -C build
rm -f ${STAGING_DIR}/usr/lib/gio/modules/giomodule.cache'''

[hooks]
post_install = "gio-querymodules /usr/lib/gio/modules"
post_upgrade = "gio-querymodules /usr/lib/gio/modules"
pre_remove = "gio-querymodules /usr/lib/gio/modules"

[[output]]
runtime_deps = ['gnutls', 'gsettings-desktop-schemas', 'libproxy', 'glib']
