[plan]
name = "npth"
version = "1.8"
release = 1
description = "New portable threads library for GnuPG"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://gnupg.org/software/npth/"

[[sources]]
uri = "https://gnupg.org/ftp/gcrypt/npth/npth-${PKG_VERSION}.tar.bz2"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr --disable-static
'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
DESTDIR=${PKG_DIR} make install
'''
