[plan]
name = "go"
version = "1.26.0"
release = 1
description = "The Go programming language"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://go.dev"

[[sources]]
uri = "https://go.dev/dl/go${PKG_VERSION}.linux-amd64.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
mkdir -p ${PKG_DIR}/usr/lib
cp -a ${BUILD_DIR} ${PKG_DIR}/usr/lib/go
mkdir -p ${PKG_DIR}/usr/bin
ln -sf ../lib/go/bin/go ${PKG_DIR}/usr/bin/go
ln -sf ../lib/go/bin/gofmt ${PKG_DIR}/usr/bin/gofmt
'''
