name = "diffutils"
version = "3.12"
release = 1
description = "Programs that show the differences between files or directories"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/diffutils/"

[dependencies]
build = ["gcc", "make"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://ftp.gnu.org/gnu/diffutils/diffutils-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
