name = "bubblewrap"
version = "0.11.1"
release = 1
description = "Unprivileged sandboxing tool"
license = "LGPL-2.0-or-later"
arch = "x86_64"
url = "https://github.com/containers/bubblewrap"

[dependencies]
build = ["meson", "ninja", "pkgconf"]
link = ["libcap", "libseccomp"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/containers/bubblewrap/releases/download/v${VERSION}/bubblewrap-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build      \
--prefix=/usr          \
--buildtype=release    \
-D tests=false'''

[lifecycle.compile]
script = '''
cd source
ninja -C build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} ninja -C build install'''
