name = "python-jinja2"
version = "3.1.6"
release = 1
description = "A simple pythonic template language"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://palletsprojects.com/p/jinja/"

[dependencies]
runtime = ["python-markupsafe", "python"]
build = ["python-markupsafe", "python", "setuptools"]

[[sources]]
uri = "https://files.pythonhosted.org/packages/source/j/jinja2/jinja2-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .

'''
