name = "liburcu"
version = "0.15.6"
release = 1
description = "Userspace RCU (read-copy-update) library"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://lttng.org/"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://lttng.org/files/urcu/userspace-rcu-${VERSION}.tar.bz2"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/userspace-rcu-${VERSION}
./configure --prefix=/usr --disable-static'''

[pipeline.compile]
script = '''
cd source/userspace-rcu-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/userspace-rcu-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
