name = "glfw"
version = "3.4"
release = 1
description = "Multi-platform library for OpenGL, OpenGL ES, Vulkan, window and input"
license = "Zlib"
arch = "x86_64"
url = "https://www.glfw.org/"

[dependencies]
build = ["cmake", "gcc", "make", "pkgconf", "wayland-protocols"]
link = ["wayland", "libxkbcommon"]
runtime = ["wayland", "libxkbcommon"]
optional = ["libdecor"]

[[sources]]
sha256 = "c038d34200234d071fae9345bc455e4a8f2f544ab60150765d7704e08f3dac01"
url = "https://github.com/glfw/glfw/archive/refs/tags/${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
cmake -B build \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_BUILD_TYPE=Release \
  -DGLFW_BUILD_WAYLAND=ON \
  -DGLFW_BUILD_X11=OFF \
  -DGLFW_LIBRARY_TYPE=SHARED \
  -DGLFW_BUILD_EXAMPLES=OFF \
  -DGLFW_BUILD_TESTS=OFF \
  -DGLFW_BUILD_DOCS=OFF'''

[lifecycle.compile]
script = '''
cd source
cmake --build build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} cmake --install build'''

[output]
provides = ["libglfw"]
