name = "mtdev"
version = "1.1.7"
release = 1
description = "Multitouch protocol translation library"
license = "MIT"
arch = "x86_64"
url = "https://bitmath.org/code/mtdev/"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://bitmath.org/code/mtdev/mtdev-${VERSION}.tar.bz2"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/mtdev-${VERSION}
./configure --prefix=/usr --disable-static'''

[pipeline.compile]
script = '''
cd source/mtdev-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/mtdev-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

