[plan]
name = "python-pluggy"
version = "1.6.0"
release = 1
description = "Plugin and hook calling mechanisms for Python"
license = "MIT"
arch = "x86_64"
url = "https://github.com/pytest-dev/pluggy"

[dependencies]
runtime = ["python"]
build = ["python", "setuptools"]

[[sources]]
uri = "https://pypi.org/packages/source/p/pluggy/pluggy-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .
'''
