name = "iniparser"
version = "4.3.0"
release = 1
description = "A free stand-alone ini file parsing library"
license = "MIT"
arch = "x86_64"
url = "https://github.com/ndevilla/iniparser"

link_deps = ['glibc']
build_deps = ['ninja', 'cmake']

[[sources]]
type = "http"
sha256 = "97375d6a3c481ebb27c47884aa57934599eed027a3015225e2f13173efd39643"
url = "https://github.com/ndevilla/iniparser/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/iniparser-${VERSION}
mkdir build
cd build
cmake \
    -G Ninja \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    ..'''

[pipeline.compile]
script = '''
cd source/iniparser-${VERSION}/build
ninja'''

[pipeline.staging]
script = '''
cd source/iniparser-${VERSION}/build
DESTDIR=${STAGING_DIR} ninja install'''

[[output]]
runtime_deps = ['glibc']
