name = "nasm"
version = "2.16.03"
release = 1
description = "The Netwide Assembler"
license = "BSD-2-Clause"
arch = "x86_64"

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/nasm-2.16.03.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/nasm-${VERSION}
./configure --prefix=/usr'''

[pipeline.compile]
script = '''
cd source/nasm-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/nasm-${VERSION}
make DESTDIR=${STAGING_DIR} install'''
