[plan]
name = "at-spi2-core"
version = "2.58.3"
release = 1
description = "Assistive Technology Service Provider Interface (includes ATK)"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://wiki.gnome.org/Accessibility"

[dependencies]
runtime = ["dbus", "systemd"]
build = ["dbus", "gobject-introspection", "meson", "ninja"]
link = ["glib"]

[[sources]]
uri = "https://download.gnome.org/sources/at-spi2-core/2.58/at-spi2-core-${PART_VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
meson setup ${BUILD_DIR}/build ${BUILD_DIR} \
--prefix=/usr               \
--buildtype=release
'''

[lifecycle.compile]
script = "ninja -C ${BUILD_DIR}/build -j$(nproc)"

[lifecycle.staging]
script = "DESTDIR=${PART_DIR} ninja -C ${BUILD_DIR}/build install"
