name = "xdg-user-dirs"
version = "0.20"
release = 1
description = "Tool to help manage standard user directories"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://gitlab.freedesktop.org/xdg/xdg-user-dirs"

[dependencies]
build = [
    "gcc",
    "gettext",
    "meson",
    "ninja",
    "pkgconf",
    "docbook-xsl",
    "libxslt",
]

[[sources]]
uri = "https://gitlab.freedesktop.org/xdg/xdg-user-dirs/-/archive/v${VERSION}/xdg-user-dirs-v${VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
meson setup build --prefix=/usr --buildtype=release
'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
meson compile -C build
'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
meson install -C build --destdir ${PART_DIR}
'''

[lifecycle.fabricate]
