name = "xdg-user-dirs"
version = "0.20"
release = 1
description = "Tool to help manage standard user directories"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://gitlab.freedesktop.org/xdg/xdg-user-dirs"


build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://gitlab.freedesktop.org/xdg/xdg-user-dirs/-/archive/v${VERSION}/xdg-user-dirs-v${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/xdg-user-dirs-${VERSION}
meson setup build --prefix=/usr --buildtype=release'''

[pipeline.compile]
script = '''
cd source/xdg-user-dirs-${VERSION}
meson compile -C build'''

[pipeline.staging]
script = '''
cd source/xdg-user-dirs-${VERSION}
meson install -C build --destdir ${STAGING_DIR}'''

