name = "lcms2"
version = "2.16"
release = 1
description = "Small-footprint color management engine"
license = "MIT"
arch = "x86_64"

[dependencies]
build = ["gcc", "make", "pkgconf"]
link = ["libjpeg-turbo"]

[[sources]]
type = "http"
sha256 = "d873d34ad8b9b4cea010631f1a6228d2087475e4dc5e763eb81acc23d9d45a51"
url = "https://github.com/mm2/Little-CMS/releases/download/lcms2.16/lcms2-2.16.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr --disable-static'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
