name = "rime-luna-pinyin"
version = "0.0.20250101"
release = 1
description = "Rime Lunar Pinyin input schema (朙月拼音)"
license = "LGPL-3.0-or-later"
arch = "any"
url = "https://github.com/rime/rime-luna-pinyin"

[dependencies]
runtime = ["rime-prelude"]

[[sources]]
sha256 = "SKIP"
url = "git+https://github.com/rime/rime-luna-pinyin.git#master"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source
install -d ${PART_DIR}/usr/share/rime-data
install -Dm644 ${WORKDIR}/*.yaml -t ${PART_DIR}/usr/share/rime-data/'''
