name = "meson"
version = "1.12.1"
release = 1
description = "High productivity build system"
license = "Apache-2.0"
arch = "x86_64"
url = "https://mesonbuild.com/"


build_deps = ['python', 'setuptools', 'python-wheel']

[[sources]]
type = "http"
sha256 = "ab0a6ca09f8ef70c564c8241fb5a23957886a0b53fb58412b5e07eaf07dba743"
url = "https://github.com/mesonbuild/meson/releases/download/${VERSION}/meson-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.staging]
script = '''
cd source/meson-${VERSION}
pip3 install --no-index --no-user --no-deps --ignore-installed --no-cache-dir --root=${STAGING_DIR} --no-build-isolation .'''

[[output]]
runtime_deps = ['python', 'ninja']
