name = "meson"
version = "1.10.2"
release = 1
description = "High productivity build system"
license = "Apache-2.0"
arch = "x86_64"
url = "https://mesonbuild.com/"


build_deps = ['python']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/mesonbuild/meson/releases/download/${VERSION}/meson-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.compile]
script = '''
cd source/meson-${VERSION}
python3 setup.py build'''

[lifecycle.staging]
script = '''
cd source/meson-${VERSION}
python3 setup.py install --root=${STAGING_DIR} --prefix=/usr --optimize=1'''

[[output]]
runtime_deps = ['python', 'ninja']
