name = "man-pages"
version = "6.15"
release = 1
description = "Linux man pages - over 2,400 manual pages documenting the Linux kernel and C library interfaces"
license = "GPL-2.0-or-later AND MIT"
arch = "x86_64"
url = "https://www.kernel.org/doc/man-pages/"

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://www.kernel.org/pub/linux/docs/man-pages/man-pages-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.prepare]
script = '''
cd source
rm -v man3/crypt*'''

[lifecycle.staging]
script = '''
cd source
make -R GIT=false prefix=/usr DESTDIR=${PART_DIR} install'''
