[plan]
name = "pass"
version = "1.7.4"
release = 1
description = "The standard unix password manager"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://www.passwordstore.org/"

[dependencies]
build = ["make"]
runtime = ["bash", "gnupg", "git"]
optional = [
  { name = "wl-clipboard", description = "copy generated passwords to Wayland clipboard" },
]

[sources]
uris = ["https://git.zx2c4.com/password-store/snapshot/password-store-${PKG_VERSION}.tar.xz"]
sha256 = ["SKIP"]

[lifecycle.package]
script = """
cd ${BUILD_DIR}
make \
    PREFIX=/usr \
    DESTDIR=${PKG_DIR} \
    install
"""
