name = "pass"
version = "1.7.4"
release = 1
description = "The standard unix password manager"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://www.passwordstore.org/"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://git.zx2c4.com/password-store/snapshot/password-store-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.staging]
script = '''
cd source/pass-${VERSION}
make PREFIX=/usr DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['bash', 'gnupg', 'git']
