name = "pass"
version = "1.7.4"
release = 1
description = "The standard unix password manager"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://www.passwordstore.org/"

[dependencies]
runtime = ["bash", "gnupg", "git"]
build = ["make"]
optional = ["wl-clipboard"]

[[sources]]
sha256 = "SKIP"
url = "https://git.zx2c4.com/password-store/snapshot/password-store-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source
make PREFIX=/usr DESTDIR=${PART_DIR} install'''
