name = "graphene"
version = "1.10.8"
release = 2
description = "Thin layer of types for graphic libraries"
license = "MIT"
arch = "x86_64"
url = "https://github.com/ebassi/graphene"

[dependencies]
build = ["gobject-introspection", "meson", "ninja"]
link = ["glib"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/graphene/1.10/graphene-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build --prefix=/usr --buildtype=release -Dintrospection=enabled -Dinstalled_tests=false -Dtests=false'''

[lifecycle.compile]
script = '''
cd source
ninja -C build'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} ninja -C build install'''
