[plan]
name = "graphene"
version = "1.10.8"
release = 2
description = "Thin layer of types for graphic libraries"
license = "MIT"
arch = "x86_64"
url = "https://github.com/ebassi/graphene"

[dependencies]
build = ["gobject-introspection", "meson", "ninja"]
link = ["glib"]

[[sources]]
uri = "https://download.gnome.org/sources/graphene/1.10/graphene-${PART_VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
meson setup build --prefix=/usr --buildtype=release -Dintrospection=enabled -Dinstalled_tests=false -Dtests=false
'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
ninja -C build
'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
DESTDIR=${PART_DIR} ninja -C build install
'''
