name = "graphene"
version = "1.10.8"
release = 2
description = "Thin layer of types for graphic libraries"
license = "MIT"
arch = "x86_64"
url = "https://github.com/ebassi/graphene"

link_deps = ['glib']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://download.gnome.org/sources/graphene/1.10/graphene-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/graphene-${VERSION}
meson setup build --prefix=/usr --buildtype=release -Dintrospection=enabled -Dinstalled_tests=false -Dtests=false'''

[pipeline.compile]
script = '''
cd source/graphene-${VERSION}
ninja -C build'''

[pipeline.staging]
script = '''
cd source/graphene-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['glib']
