[plan]
name = "p11-kit"
version = "0.26.2"
release = 2
description = "Library for loading and sharing PKCS#11 modules"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://p11-glue.github.io/p11-glue/p11-kit.html"

[dependencies]
build = ["meson", "ninja", "pkgconf"]
runtime = ["libtasn1"]
link = ["libtasn1", "libffi"]

[sources]
uris = ["https://github.com/p11-glue/p11-kit/releases/download/${PKG_VERSION}/p11-kit-${PKG_VERSION}.tar.xz"]
sha256 = ["SKIP"]

[lifecycle.configure]
dockyard = "none"
script = '''
meson setup ${BUILD_DIR}/build ${BUILD_DIR} \
--prefix=/usr               \
--buildtype=release         \
-D trust_paths=/etc/pki/anchors
'''

[lifecycle.compile]
dockyard = "none"
script = "ninja -C ${BUILD_DIR}/build -j$(nproc)"

[lifecycle.package]
dockyard = "none"
script = "DESTDIR=${PKG_DIR} ninja -C ${BUILD_DIR}/build install"
