name = "python-wcwidth"
version = "0.6.0"
release = 1
description = "Measures the displayed width of unicode strings in a terminal"
license = "MIT"
arch = "x86_64"
url = "https://github.com/jquast/wcwidth"

[dependencies]
runtime = ["python"]
build = ["python", "setuptools"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://pypi.org/packages/source/w/wcwidth/wcwidth-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source/wcwidth-${VERSION}
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .'''
