name = "hicolor-icon-theme"
version = "0.18"
release = 2
description = "Freedesktop fallback icon theme"
license = "GPL-2.0-or-later"
arch = "any"
url = "https://icon-theme.freedesktop.org/"

[dependencies]
build = ["meson", "ninja"]

[[sources]]
sha256 = "SKIP"
url = "https://icon-theme.freedesktop.org/releases/hicolor-icon-theme-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build --prefix=/usr --buildtype=release'''

[lifecycle.compile]
script = '''
cd source
meson compile -C ${WORKDIR}/build'''

[lifecycle.staging]
script = '''
cd source
meson install -C ${WORKDIR}/build --destdir ${PART_DIR}'''

[hooks]
post_install = "gtk-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || true"
post_upgrade = "gtk-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || true"
