name = "hicolor-icon-theme"
version = "0.18"
release = 2
description = "Freedesktop fallback icon theme"
license = "GPL-2.0-or-later"
arch = "any"
url = "https://icon-theme.freedesktop.org/"


build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://icon-theme.freedesktop.org/releases/hicolor-icon-theme-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/hicolor-icon-theme-${VERSION}
meson setup build --prefix=/usr --buildtype=release'''

[pipeline.compile]
script = '''
cd source/hicolor-icon-theme-${VERSION}
meson compile -C build'''

[pipeline.staging]
script = '''
cd source/hicolor-icon-theme-${VERSION}
meson install -C build --destdir ${STAGING_DIR}'''

[[output]]

[output.hooks]
post_install = "gtk-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || true"
post_upgrade = "gtk-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || true"
