[plan]
name = "tmux"
version = "3.6a"
release = 1
description = "A terminal multiplexer"
license = "ISC"
arch = "x86_64"
url = "https://github.com/tmux/tmux/wiki"

[dependencies]
build = ["gcc", "make"]
link = ["libevent", "ncurses", "systemd"]

[[sources]]
uri = "https://github.com/tmux/tmux/releases/download/${PKG_VERSION}/tmux-${PKG_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr \
            --enable-sixel   \
            --enable-systemd
'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PKG_DIR} install
'''
