name = "tmux"
version = "3.6a"
release = 1
description = "A terminal multiplexer"
license = "ISC"
arch = "x86_64"
url = "https://github.com/tmux/tmux/wiki"

link_deps = ['libevent', 'ncurses', 'systemd']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/tmux/tmux/releases/download/${VERSION}/tmux-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/tmux-${VERSION}
./configure --prefix=/usr \
            --enable-sixel   \
            --enable-systemd'''

[pipeline.compile]
script = '''
cd source/tmux-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/tmux-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['libevent', 'ncurses', 'systemd']
