[plan]
name = "tar"
version = "1.35"
release = 1
description = "An archiving program for creating and extracting tar archives"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/tar/"

[dependencies]
build = ["gcc", "make"]
[sources]
uris = ["https://ftp.gnu.org/gnu/tar/tar-${PKG_VERSION}.tar.xz"]
sha256 = ["SKIP"]

[lifecycle.configure]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
FORCE_UNSAFE_CONFIGURE=1 \
./configure --prefix=/usr
'''

[lifecycle.compile]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
'''

[lifecycle.check]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make check
'''

[lifecycle.package]
dockyard = "none"
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PKG_DIR} install
make -C doc DESTDIR=${PKG_DIR} install-html docdir=/usr/share/doc/tar-1.35
'''
