[plan]
name = "emacs"
version = "30.2"
release = 1
description = "The extensible, customizable, self-documenting real-time display editor"
license = "GPL-3.0-or-later"
arch = "x86_64"
url = "https://www.gnu.org/software/emacs/"

[dependencies]
runtime = ["gnutls", "tree-sitter"]
build = ["gcc", "gnutls", "make", "pkgconf", "tree-sitter"]
link = ["glib", "glibc", "ncurses"]

[[sources]]
uri = "https://ftp.gnu.org/gnu/emacs/emacs-${PKG_VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr            \
--with-json              \
--with-tree-sitter       \
--with-native-compilation=no \
--without-x              \
--without-xpm            \
--without-jpeg           \
--without-tiff           \
--without-gif            \
--without-png            \
--without-rsvg           \
--without-imagemagick    \
--without-gconf          \
--without-gsettings      \
--with-gnutls
'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)
'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PKG_DIR} install
'''
