name = "tcpdump"
version = "4.99.6"
release = 1
description = "Command-line packet analyzer"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://www.tcpdump.org/"

[dependencies]
build = ["gcc", "make", "libpcap"]
link = ["libpcap"]

[[sources]]
sha256 = "SKIP"
url = "https://www.tcpdump.org/release/tcpdump-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install'''
