name = "python-requests"
version = "2.33.1"
release = 1
description = "Python HTTP for Humans"
license = "Apache-2.0"
arch = "x86_64"
url = "https://requests.readthedocs.io/"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://pypi.org/packages/source/r/requests/requests-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source
pip3 install --no-index --no-user --no-deps --root=${STAGING_DIR} --no-build-isolation .'''

[output]
runtime_deps = ['python:default', 'python-charset-normalizer:default', 'python-idna:default', 'python-urllib3:default', 'python-certifi:default']
