name = "python-certifi"
version = "2026.2.25"
release = 1
description = "Python package for providing Mozilla's CA Bundle"
license = "MPL-2.0"
arch = "x86_64"
url = "https://github.com/certifi/python-certifi"

[dependencies]
runtime = ["python"]
build = ["python", "setuptools"]

[[sources]]
sha256 = "SKIP"
url = "https://pypi.org/packages/source/c/certifi/certifi-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
script = '''
cd source
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .'''
