name = "fribidi"
version = "1.0.16"
release = 1
description = "Unicode Bidirectional Algorithm library"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://github.com/fribidi/fribidi"

[[sources]]
uri = "https://github.com/fribidi/fribidi/releases/download/v${PART_VERSION}/fribidi-${PART_VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
meson setup ${BUILD_DIR}/build ${BUILD_DIR} \
--prefix=/usr          \
--buildtype=release

'''

[lifecycle.compile]
script = "ninja -C ${BUILD_DIR}/build -j$(nproc)"

[lifecycle.staging]
script = "DESTDIR=${PART_DIR} ninja -C ${BUILD_DIR}/build install"
