name = "ostree"
version = "2025.7"
release = 2
description = "Operating system and container binary deployment and upgrades"
license = "LGPL-2.0-or-later"
arch = "x86_64"
url = "https://ostreedev.github.io/ostree/"

[dependencies]
runtime = ["systemd"]
build = ["gcc", "make", "pkgconf", "gettext"]
link = ["glib", "libarchive", "curl", "gpgme"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/ostreedev/ostree/releases/download/v${VERSION}/libostree-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr       \
    --disable-static            \
    --with-curl                 \
    --without-soup              \
    --without-soup3             \
    --disable-man               \
    --disable-gtk-doc           \
    --with-gpgme                \
    --sysconfdir=/etc            \
    --disable-otmpfile          \
    --with-builtin-grub2-mkconfig'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} make install'''
