name = "harfbuzz"
version = "14.1.0"
release = 1
description = "OpenType text shaping engine"
license = "MIT"
arch = "x86_64"

link_deps = ['cairo', 'freetype', 'glib', 'icu', 'graphite2']
build_deps = ['meson', 'ninja', 'pkgconf']

[[sources]]
type = "http"
sha256 = "ee0eb3a1da2c5a28147f12dff55f6c7d60aeeeb29ac7ef334eabe84c8476c105"
url = "https://github.com/harfbuzz/harfbuzz/releases/download/${VERSION}/harfbuzz-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/harfbuzz-${VERSION}
meson setup build \
    --prefix=/usr          \
    --buildtype=release    \
    --wrap-mode=nofallback \
    -D cairo=enabled       \
    -D icu=enabled         \
    -D glib=enabled        \
    -D gobject=enabled     \
    -D graphite2=enabled   \
    -D tests=disabled      \
    -D docs=disabled'''

[lifecycle.compile]
script = '''
cd source/harfbuzz-${VERSION}/build
ninja -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/harfbuzz-${VERSION}/build
DESTDIR=${STAGING_DIR} ninja install'''

[[output]]
runtime_deps = ['cairo', 'freetype', 'glib', 'icu', 'graphite2']
