name = "harfbuzz"
version = "14.1.0"
release = 1
description = "OpenType text shaping engine"
license = "MIT"
arch = "x86_64"

[dependencies]
build = ["gobject-introspection", "meson", "ninja", "pkgconf", "graphite2"]
link = ["cairo", "freetype", "glib", "icu", "graphite2"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/harfbuzz/harfbuzz/releases/download/12.3.2/harfbuzz-12.3.2.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build \
    --prefix=/usr          \
    --buildtype=release    \
    --wrap-mode=nofallback \
    -D cairo=enabled       \
    -D icu=enabled         \
    -D glib=enabled        \
    -D gobject=enabled     \
    -D graphite2=enabled   \
    -D tests=disabled      \
    -D docs=disabled'''

[lifecycle.compile]
script = '''
cd source/build
ninja -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/build
DESTDIR=${PART_DIR} ninja install'''
