name = "libpciaccess"
version = "0.18.1"
release = 1
description = "X11 PCI access library"
license = "MIT"
arch = "x86_64"
url = "https://gitlab.freedesktop.org/xorg/lib/libpciaccess"

[dependencies]
build = ["meson", "ninja"]
link = ["glibc", "zlib"]

[[sources]]
sha256 = "4af43444b38adb5545d0ed1c2ce46d9608cc47b31c2387fc5181656765a6fa76"
url = "https://xorg.freedesktop.org/releases/individual/lib/libpciaccess-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup ${WORKDIR}/build ${WORKDIR} \
    --prefix=/usr \
    --buildtype=release'''

[lifecycle.compile]
script = '''
cd source
ninja -C ${WORKDIR}/build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} ninja -C ${WORKDIR}/build install'''
