name = "dhcpcd"
version = "10.3.0"
release = 1
description = "DHCP/DHCPv6 client with IPv4LL support"
license = "BSD-2-Clause"
arch = "x86_64"
url = "https://github.com/NetworkConfiguration/dhcpcd"

[dependencies]
build = ["gcc", "make"]

[[sources]]
uri = "https://github.com/NetworkConfiguration/dhcpcd/releases/download/v${PART_VERSION}/dhcpcd-${PART_VERSION}.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr       \
--sbindir=/usr/bin  \
--sysconfdir=/etc   \
--libexecdir=/usr/lib/dhcpcd \
--dbdir=/var/lib/dhcpcd      \
--runstatedir=/run           \
--disable-privsep

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install

'''

[lifecycle.fabricate]
