name = "libaio"
version = "0.3.113"
release = 1
description = "Linux kernel AIO (Asynchronous I/O) interface library"
license = "LGPL-2.0-or-later"
arch = "x86_64"
url = "https://pagure.io/libaio"

[[sources]]
uri = "https://pagure.io/libaio/archive/libaio-${VERSION}/libaio-libaio-${VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.compile]
script = "make -j$(nproc) -C ${BUILD_DIR} prefix=/usr"

[lifecycle.staging]
script = "make -C ${BUILD_DIR} prefix=/usr DESTDIR=${PART_DIR} install"

[lifecycle.fabricate]
