name = "cmake"
version = "4.3.2"
release = 1
description = "A modern toolset used for generating Makefiles and other build systems"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://cmake.org/"


[[sources]]
type = "http"
sha256 = "b0231eb39b3c3cabdc568c619df78208a7bd95ea10c9b2236d61218bac1b367d"
url = "https://cmake.org/files/v4.3/cmake-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/cmake-${VERSION}
sed -i '/"lib64"/s/64//' Modules/GNUInstallDirs.cmake
./bootstrap --prefix=/usr \
--no-system-jsoncpp \
--no-system-cppdap \
--no-system-librhash \
--mandir=/share/man \
--docdir=/share/doc/cmake-${VERSION} \
--parallel=$(nproc)'''

[lifecycle.compile]
script = '''
cd source/cmake-${VERSION}
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/cmake-${VERSION}
make DESTDIR=${STAGING_DIR} install'''
