name = "cmake"
version = "4.3.1"
release = 1
description = "A modern toolset used for generating Makefiles and other build systems"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://cmake.org/"

[dependencies]
build = ["gcc", "make"]

[[sources]]
uri = "https://cmake.org/files/v4.3/cmake-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
sed -i '/"lib64"/s/64//' Modules/GNUInstallDirs.cmake
./bootstrap --prefix=/usr \
--no-system-jsoncpp \
--no-system-cppdap \
--no-system-librhash \
--mandir=/share/man \
--docdir=/share/doc/cmake-${PART_VERSION} \
--parallel=$(nproc)

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install

'''

[lifecycle.fabricate]
