name = "libbytesize"
version = "2.12"
release = 1
description = "Library for working with sizes in bytes"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://github.com/storaged-project/libbytesize"

link_deps = ['glib:default', 'mpfr:default', 'pcre2:default']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/storaged-project/libbytesize/releases/download/${VERSION}/libbytesize-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
./configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${STAGING_DIR} install'''

