name = "containers-common"
version = "0.64.1"
release = 1
description = "Common configuration files for Podman and related container tools"
license = "Apache-2.0"
arch = "x86_64"
url = "https://github.com/containers/common"

[[sources]]
type = "http"
sha256 = "414def665a172a4d79366dc594e5313d43d672ba19009aa2a3dd78272e277506"
url = "https://github.com/containers/common/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.staging]
isolation = "none"
script = '''
cd source/common-${VERSION}

install -dm755 ${PART_DIR}/etc/containers/certs.d
install -dm755 ${PART_DIR}/etc/containers/networks
install -dm755 ${PART_DIR}/etc/containers/oci/hooks.d
install -dm755 ${PART_DIR}/etc/containers/registries.conf.d
install -dm755 ${PART_DIR}/etc/containers/registries.d
install -dm755 ${PART_DIR}/etc/containers/systemd
install -dm755 ${PART_DIR}/usr/share/containers
install -dm755 ${PART_DIR}/usr/share/containers/systemd
install -dm700 ${PART_DIR}/usr/lib/containers/storage/overlay-images
install -dm700 ${PART_DIR}/usr/lib/containers/storage/overlay-layers
touch ${PART_DIR}/usr/lib/containers/storage/overlay-images/images.lock
touch ${PART_DIR}/usr/lib/containers/storage/overlay-layers/layers.lock

install -Dm644 pkg/config/containers.conf ${PART_DIR}/usr/share/containers/containers.conf
install -Dm644 vendor/github.com/containers/storage/storage.conf ${PART_DIR}/usr/share/containers/storage.conf
install -Dm644 pkg/subscriptions/mounts.conf ${PART_DIR}/usr/share/containers/mounts.conf
install -Dm644 pkg/seccomp/seccomp.json ${PART_DIR}/usr/share/containers/seccomp.json
install -Dm644 tests/policy.json ${PART_DIR}/etc/containers/policy.json

cat > ${PART_DIR}/etc/containers/registries.conf << 'EOF'
unqualified-search-registries = ["docker.io", "quay.io", "registry.fedoraproject.org"]
short-name-mode = "permissive"
EOF'''

[output]
backup = ["/etc/containers/policy.json", "/etc/containers/registries.conf"]
