[plan]
name = "rtkit"
version = "0.14"
release = 5
description = "Realtime Policy and Watchdog Daemon"
license = "GPL-3.0-or-later AND MIT"
arch = "x86_64"
url = "https://gitlab.freedesktop.org/pipewire/rtkit"

[dependencies]
build = ["gcc", "meson", "ninja", "pkgconf", "vim"]
link = ["dbus", "libcap", "polkit", "systemd"]

[sources]
uris = ["git+https://gitlab.freedesktop.org/pipewire/rtkit.git#tag=v${PKG_VERSION}"]
sha256 = ["SKIP"]

[lifecycle.configure]
dockyard = "none"
script = '''
meson setup ${BUILD_DIR}/build ${BUILD_DIR} \
  --prefix=/usr \
  --sbindir=/usr/bin \
  --buildtype=release \
  -D installed_tests=false
'''

[lifecycle.compile]
dockyard = "none"
script = "meson compile -C ${BUILD_DIR}/build -j$(nproc)"

[lifecycle.package]
dockyard = "none"
script = '''
DESTDIR=${PKG_DIR} meson install -C ${BUILD_DIR}/build

install -Dm644 ${BUILD_DIR}/LICENSE -t ${PKG_DIR}/usr/share/licenses/rtkit/
sed -n '4,25p' ${BUILD_DIR}/rtkit.c |
  install -Dm644 /dev/stdin ${PKG_DIR}/usr/share/licenses/rtkit/LICENSE.MIT

if [ -d ${PKG_DIR}/usr/sbin ]; then
  cp -a ${PKG_DIR}/usr/sbin/. ${PKG_DIR}/usr/bin/
  rm -rf ${PKG_DIR}/usr/sbin
fi
'''

[install_scripts]
post_install = '''
systemd-sysusers /usr/lib/sysusers.d/rtkit.conf
systemctl daemon-reload
systemctl enable --now rtkit-daemon.service
'''
post_upgrade = '''
systemd-sysusers /usr/lib/sysusers.d/rtkit.conf
systemctl daemon-reload
systemctl restart rtkit-daemon.service
'''
