name = "python-markupsafe"
version = "3.0.2"
release = 1
description = "Python module that implements XML/HTML/XHTML Markup safe string"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://palletsprojects.com/p/markupsafe/"

[dependencies]
runtime = ["python"]
build = ["python", "setuptools"]

[[sources]]
uri = "https://files.pythonhosted.org/packages/source/m/markupsafe/markupsafe-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .

'''
