name = "python-markupsafe"
version = "3.0.3"
release = 1
description = "Python module that implements XML/HTML/XHTML Markup safe string"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://palletsprojects.com/p/markupsafe/"


build_deps = ['python']

[[sources]]
type = "http"
sha256 = "722695808f4b6457b320fdc131280796bdceb04ab50fe1795cd540799ebe1698"
url = "https://files.pythonhosted.org/packages/source/m/markupsafe/markupsafe-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.staging]
script = '''
cd source/markupsafe-${VERSION}
pip3 install --no-index --no-user --no-deps --ignore-installed --root=${STAGING_DIR} --no-build-isolation .'''

[[output]]
runtime_deps = ['python']
