name = "inih"
version = "r58"
release = 1
description = "Simple INI file parser library in C"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://github.com/benhoyt/inih"


build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/benhoyt/inih/archive/refs/tags/${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/inih-${VERSION}
meson setup build --prefix=/usr --buildtype=release -Ddefault_library=shared -Ddistro_install=true'''

[pipeline.compile]
script = '''
cd source/inih-${VERSION}
meson compile -C build'''

[pipeline.staging]
script = '''
cd source/inih-${VERSION}
meson install -C build --destdir ${STAGING_DIR}'''

