name = "spirv-cross"
version = "1.4.350.1"
release = 1
description = "Tool and library for parsing and converting SPIR-V to other shader languages"
license = "Apache-2.0"
arch = "x86_64"
url = "https://github.com/KhronosGroup/SPIRV-Cross"


build_deps = ['cmake']

[[sources]]
type = "http"
sha256 = "21057934ede32fe90a63dc304fdce0f2a6cb4f0ca685a72ed36a73aac6f72ad5"
url = "https://github.com/KhronosGroup/SPIRV-Cross/archive/refs/tags/vulkan-sdk-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/SPIRV-Cross-vulkan-sdk-${VERSION}
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release \
      -DSPIRV_CROSS_SHARED=ON \
      -DSPIRV_CROSS_STATIC=OFF \
      -DSPIRV_CROSS_CLI=OFF \
      ..'''

[pipeline.compile]
script = '''
cd source/SPIRV-Cross-vulkan-sdk-${VERSION}/build
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/SPIRV-Cross-vulkan-sdk-${VERSION}/build
make DESTDIR=${STAGING_DIR} install'''

