name = "popt"
version = "1.19"
release = 1
description = "C library for parsing command line parameters"
license = "MIT"
arch = "x86_64"
url = "https://github.com/rpm-software-management/popt"

link_deps = ['glibc']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://ftp.osuosl.org/pub/rpm/popt/releases/popt-1.x/popt-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/popt-${VERSION}
./configure --prefix=/usr'''

[lifecycle.compile]
script = '''
cd source/popt-${VERSION}
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/popt-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['glibc']
