link_deps = ['cairo:default', 'gdk-pixbuf:default', 'pango:default', 'glib:default', 'libxml2:default', 'harfbuzz:default', 'freetype:default', 'fribidi:default']

[lifecycle.configure]
dockyard = "relaxed"
script = '''
cd source
meson setup build --prefix=/usr --libdir=lib --buildtype=release -Dintrospection=enabled -Ddocs=disabled -Dtests=false -Dvala=disabled'''

