name = "xdg-dbus-proxy"
version = "0.1.6"
release = 1
description = "D-Bus proxy for Flatpak sandboxed apps"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://github.com/flatpak/xdg-dbus-proxy"

[dependencies]
runtime = ["dbus"]
build = ["meson", "ninja", "pkgconf"]
link = ["glib"]

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/flatpak/xdg-dbus-proxy/releases/download/${VERSION}/xdg-dbus-proxy-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build      \
--prefix=/usr          \
--buildtype=release    \
-D tests=false         \
-D man=disabled'''

[lifecycle.compile]
script = '''
cd source
ninja -C build -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} ninja -C build install'''
