name = "xdg-dbus-proxy"
version = "0.1.6"
release = 1
description = "D-Bus proxy for Flatpak sandboxed apps"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://github.com/flatpak/xdg-dbus-proxy"

link_deps = ['glib']
build_deps = ['meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/flatpak/xdg-dbus-proxy/releases/download/${VERSION}/xdg-dbus-proxy-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/xdg-dbus-proxy-${VERSION}
meson setup build      \
--prefix=/usr          \
--buildtype=release    \
-D tests=false         \
-D man=disabled'''

[pipeline.compile]
script = '''
cd source/xdg-dbus-proxy-${VERSION}
ninja -C build -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/xdg-dbus-proxy-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['dbus', 'glib']
