name = "python-packaging"
version = "26.2"
release = 1
description = "Core utilities for Python packages"
license = "Apache-2.0"
arch = "x86_64"
url = "https://packaging.pypa.io/"


build_deps = ['python']

[[sources]]
type = "http"
sha256 = "ff452ff5a3e828ce110190feff1178bb1f2ea2281fa2075aadb987c2fb221661"
url = "https://pypi.org/packages/source/p/packaging/packaging-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.staging]
script = '''
cd source/packaging-${VERSION}
pip3 install --no-index --no-user --no-deps --ignore-installed --no-cache-dir --root=${STAGING_DIR} --no-build-isolation .'''

[[output]]
runtime_deps = ['python']
