[plan]
name = "python-packaging"
version = "25.0"
release = 1
description = "Core utilities for Python packages"
license = "Apache-2.0"
arch = "x86_64"
url = "https://packaging.pypa.io/"
replaces = ["packaging"]

[dependencies]
runtime = ["python"]
build = ["flit-core", "python"]

[[sources]]
uri = "https://pypi.org/packages/source/p/packaging/packaging-${PART_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
pip3 install --no-index --no-user --no-deps --root=${PART_DIR} --no-build-isolation .
'''
