name = "libvpx"
version = "1.16.0"
release = 1
description = "WebM VP8/VP9 codec SDK"
license = "BSD-3-Clause"
arch = "x86_64"
url = "https://github.com/webmproject/libvpx"


[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://github.com/webmproject/libvpx/archive/refs/tags/v${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source/libvpx-${VERSION}
./configure --prefix=/usr \
            --enable-shared \
            --disable-static \
            --enable-vp8 \
            --enable-vp9 \
            --enable-runtime-cpu-detect \
            --enable-postproc'''

[lifecycle.compile]
script = '''
cd source/libvpx-${VERSION}
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source/libvpx-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

