name = "foot"
version = "1.26.1"
release = 1
description = "A fast, lightweight and minimalistic Wayland terminal emulator"
license = "MIT"
arch = "x86_64"
url = "https://codeberg.org/dnkl/foot"

[dependencies]
runtime = ["fcft", "pixman"]
build = ["fcft", "gcc", "meson", "ninja", "pixman", "tllist"]
link = ["fontconfig", "freetype", "harfbuzz", "libxkbcommon", "ncurses", "utf8proc", "wayland", "wayland-protocols"]

[[sources]]
sha256 = "SKIP"
url = "https://codeberg.org/dnkl/foot/releases/download/${VERSION}/foot-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build --prefix=/usr --buildtype=release -Dime=true -Dthemes=true -Dwerror=false'''

[lifecycle.compile]
script = '''
cd source
ninja -C build'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} ninja -C build install'''
