name = "foot"
version = "1.26.1"
release = 1
description = "A fast, lightweight and minimalistic Wayland terminal emulator"
license = "MIT"
arch = "x86_64"
url = "https://codeberg.org/dnkl/foot"

link_deps = ['fontconfig', 'freetype', 'harfbuzz', 'libxkbcommon', 'ncurses', 'utf8proc', 'wayland']
build_deps = ['wayland-protocols', 'meson', 'ninja']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://codeberg.org/dnkl/foot/releases/download/${VERSION}/foot-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/foot-${VERSION}
meson setup build --prefix=/usr --buildtype=release -Dime=true -Dthemes=true -Dwerror=false'''

[pipeline.compile]
script = '''
cd source/foot-${VERSION}
ninja -C build'''

[pipeline.staging]
script = '''
cd source/foot-${VERSION}
DESTDIR=${STAGING_DIR} ninja -C build install'''

[[output]]
runtime_deps = ['fcft', 'pixman', 'fontconfig', 'freetype', 'harfbuzz', 'libxkbcommon', 'ncurses', 'utf8proc', 'wayland']
