name = "libmad"
version = "0.16.4"
release = 1
description = "High-quality MPEG audio decoder"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://codeberg.org/tenacityteam/libmad"

[dependencies]
build = ["cmake", "ninja", "pkgconf"]

[[sources]]
uri = "https://deb.debian.org/debian/pool/main/libm/libmad/libmad_${PART_VERSION}.orig.tar.xz"
sha256 = "SKIP"

[lifecycle.configure]
script = '''
cmake -S ${BUILD_DIR} -B ${BUILD_DIR}/build -G Ninja \
  -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
  -DCMAKE_BUILD_TYPE=None \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DBUILD_SHARED_LIBS=ON

'''

[lifecycle.compile]
script = '''
cmake --build ${BUILD_DIR}/build

'''

[lifecycle.staging]
script = '''
DESTDIR=${PART_DIR} cmake --install ${BUILD_DIR}/build

'''

[lifecycle.fabricate]
