name = "curl"
version = "8.19.0"
release = 1
description = "Command line tool and library for transferring data with URLs"
license = "curl"
arch = "x86_64"
url = "https://curl.se/"

[dependencies]
runtime = ["ca-certificates"]
build = ["gcc", "make"]
link = [
    "libidn2",
    "libpsl",
    "nghttp2",
    "openssl",
]

[[sources]]
uri = "https://curl.se/download/curl-${PART_VERSION}.tar.xz"
sha256 = "4eb41489790d19e190d7ac7e18e82857cdd68af8f4e66b292ced562d333f11df"

[lifecycle.configure]
script = '''
cd ${BUILD_DIR}
./configure --prefix=/usr                    \
--disable-static                 \
--with-openssl                   \
--enable-threaded-resolver       \
--with-ca-path=/etc/ssl/certs

'''

[lifecycle.compile]
script = '''
cd ${BUILD_DIR}
make -j$(nproc)

'''

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
make DESTDIR=${PART_DIR} install

'''

[lifecycle.fabricate]
