[plan]
name = "python-sphinx-rtd-theme"
version = "2.0.0"
release = 1
description = "Read the Docs theme for Sphinx"
license = "MIT"
arch = "x86_64"
url = "https://github.com/readthedocs/sphinx_rtd_theme"

[dependencies]
runtime = ["python", "python-sphinx", "python-sphinxcontrib-jquery"]
build = ["python", "setuptools-scm", "setuptools", "wheel"]

[[sources]]
uri = "https://github.com/readthedocs/sphinx_rtd_theme/archive/refs/tags/${PKG_VERSION}.tar.gz"
sha256 = "SKIP"

[lifecycle.staging]
script = '''
cd ${BUILD_DIR}
SETUPTOOLS_SCM_PRETEND_VERSION=${PKG_VERSION} pip3 install --no-index --no-user --no-deps --root=${PKG_DIR} --no-build-isolation .
'''
