name = "cryptsetup"
version = "2.8.6"
release = 3
description = "Userspace setup tool for transparent encryption of block devices using dm-crypt"
license = "GPL-2.0-or-later"
arch = "x86_64"
url = "https://gitlab.com/cryptsetup/cryptsetup"

link_deps = ['glibc', 'json-c', 'lvm2', 'openssl', 'popt', 'util-linux']
build_deps = ['lvm2']

[[sources]]
type = "http"
sha256 = "SKIP"
url = "https://www.kernel.org/pub/linux/utils/cryptsetup/v2.8/cryptsetup-${VERSION}.tar.xz"
extract_to = "source"

[pipeline.configure]
script = '''
cd source/cryptsetup-${VERSION}
./configure --prefix=/usr --sbindir=/usr/bin --disable-ssh-token --disable-static'''

[pipeline.compile]
script = '''
cd source/cryptsetup-${VERSION}
make -j$(nproc)'''

[pipeline.staging]
script = '''
cd source/cryptsetup-${VERSION}
make DESTDIR=${STAGING_DIR} install'''

[[output]]
runtime_deps = ['lvm2', 'glibc', 'json-c', 'openssl', 'popt', 'util-linux']
