name = "xdg-desktop-portal"
version = "1.20.4"
release = 1
description = "Portal frontend service for Flatpak and other desktop-neutral applications"
license = "LGPL-2.1-or-later"
arch = "x86_64"

[dependencies]
runtime = ["dbus", "systemd"]
build = ["gobject-introspection", "meson", "ninja", "pkgconf"]
link = ["glib", "gstreamer", "gst-plugins-base", "json-glib", "gdk-pixbuf", "libfuse3", "pipewire"]

[[sources]]
sha256 = "SKIP"
url = "https://github.com/flatpak/xdg-desktop-portal/releases/download/${VERSION}/xdg-desktop-portal-${VERSION}.tar.xz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
meson setup build --prefix=/usr --sysconfdir=/etc --localstatedir=/var --buildtype=release -Dsystemd=enabled -Dgeoclue=disabled -Dman-pages=disabled -Dtests=disabled'''

[lifecycle.compile]
script = '''
cd source
ninja -C build'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} ninja -C build install'''
