name = "python-wheel"
version = "0.48.0"
release = 1
description = "Built-package format for Python"
license = "MIT"
arch = "any"
url = "https://wheel.readthedocs.io/"


build_deps = ['python', 'flit-core']

[[sources]]
type = "http"
sha256 = "94800765601e9171bf5d58d066e640662842bcedcbab982b2c90787a2c987322"
url = "https://pypi.org/packages/source/w/wheel/wheel-${VERSION}.tar.gz"
extract_to = "source"

[pipeline.staging]
script = '''
cd source/wheel-${VERSION}
pip3 install --no-index --no-user --no-deps --ignore-installed --no-cache-dir --root=${STAGING_DIR} --no-build-isolation .'''

[[output]]
runtime_deps = ['python', 'python-packaging']
