name = "imv"
version = "5.0.1"
release = 1
description = "Command line image viewer for tiling window managers"
license = "MIT"
arch = "x86_64"
url = "https://git.sr.ht/~exec64/imv"

[dependencies]
runtime = ["wayland"]
build = ["meson", "ninja", "pkgconf", "wayland-protocols"]
link = ["pango", "libxkbcommon", "inih", "wayland", "mesa", "libpng", "libjpeg-turbo", "libtiff", "librsvg", "libheif", "libjxl", "libwebp", "icu"]

[[sources]]
sha256 = "SKIP"
url = "https://git.sr.ht/~exec64/imv/archive/v${VERSION}.tar.gz"
extract_to = "source"

[[sources]]
sha256 = "SKIP"
type = "local"
path = "patches/fix-missing-stdio.patch"

[lifecycle.prepare]
script = '''
cd source
patch -Np1 < ${WORKDIR}/fix-missing-stdio.patch'''

[lifecycle.configure]
script = '''
cd source
meson setup build \
    --prefix=/usr \
    -Dwindows=wayland \
    -Dunicode=icu \
    -Dlibnsgif=disabled \
    -Dlibnsbmp=disabled \
    -Dtest=disabled \
    -Dman=disabled'''

[lifecycle.compile]
script = '''
cd source
ninja -C build'''

[lifecycle.staging]
script = '''
cd source
DESTDIR=${PART_DIR} ninja -C build install'''
