name = "libblockdev"
version = "3.4.0"
release = 1
description = "Library for manipulating block devices"
license = "LGPL-2.1-or-later"
arch = "x86_64"
url = "https://github.com/storaged-project/libblockdev"

[dependencies]
runtime = ["mdadm"]
build = ["autoconf", "autoconf-archive", "automake", "gcc", "libtool", "make", "pkgconf", "python", "setuptools"]
link = ["btrfs-progs", "cryptsetup", "glib", "json-glib", "keyutils", "kmod", "libatasmart", "libbytesize", "libnvme", "libyaml", "lvm2", "util-linux"]

[[sources]]
type = "http"
sha256 = "65ef9a37babd44b85b8ff9b273f90f9f7d5f8ff7b0c76a8edb69240325fd83f4"
url = "https://github.com/storaged-project/libblockdev/releases/download/${VERSION}/libblockdev-${VERSION}.tar.gz"
extract_to = "source"

[lifecycle.configure]
script = '''
cd source
autoreconf -fi
./configure --prefix=/usr \
  --with-gtk-doc=no \
  --with-escrow=no \
  --with-mpath=no \
  --with-tools=no \
  --with-nvdimm=no \
  --with-nvme=yes \
  --with-smartmontools=no'''

[lifecycle.compile]
script = '''
cd source
make -j$(nproc)'''

[lifecycle.staging]
script = '''
cd source
make DESTDIR=${PART_DIR} install

if [ -d ${PART_DIR}/usr/etc ]; then
  mkdir -p ${PART_DIR}/etc
  cp -a ${PART_DIR}/usr/etc/. ${PART_DIR}/etc/
  rm -rf ${PART_DIR}/usr/etc
fi'''
