name = "ca-certificates"
version = "3.121"
release = 1
description = "Mozilla's set of trusted CA certificates"
license = "MPL-2.0"
arch = "any"
url = "https://firefox-source-docs.mozilla.org/security/nss/index.html"

[dependencies]
runtime = ["p11-kit"]
build = ["python"]

[[sources]]
sha256 = "SKIP"
url = "https://archive.mozilla.org/pub/security/nss/releases/NSS_3_121_RTM/src/nss-${VERSION}.tar.gz"
extract_to = "source"

[[sources]]
sha256 = "SKIP"
type = "local"
path = "certdata2pem.py"

[[sources]]
sha256 = "SKIP"
type = "local"
path = "bundle.sh"

[lifecycle.compile]
script = '''
cd source
mkdir -p certs
ln -sf ${WORKDIR}/nss/lib/ckfw/builtins/certdata.txt certs/certdata.txt
ln -sf ${WORKDIR}/nss/lib/ckfw/builtins/nssckbi.h certs/nssckbi.h

cd certs
python3 ${WORKDIR}/certdata2pem.py

cd source
sh ${WORKDIR}/bundle.sh'''

[lifecycle.staging]
script = '''
cd source
install -Dm644 ca-bundle.trust.p11-kit \
  ${PART_DIR}/usr/share/ca-certificates/trust-source/mozilla.trust.p11-kit'''

[hooks]
post_install = '''
update-ca-trust

'''
post_upgrade = '''
update-ca-trust

'''
